In [1]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.13/dist-packages (4.0.4)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.13/dist-packages (from pyspark) (0.10.9.9)

In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder \
   .appName("Working with dataframes") \
   .getOrCreate()

In [4]:
from google.colab import files
uploaded = files.upload()

Saving machine_master.csv to machine_master (1).csv

In [5]:
from google.colab import files
uploaded = files.upload()

Saving manufacturing_production_extra_12k.csv to manufacturing_production_extra_12k.csv

In [6]:
from google.colab import files
uploaded = files.upload()

Saving manufacturing_production_120k.csv to manufacturing_production_120k.csv

In [7]:
from google.colab import files
uploaded = files.upload()

Saving plant_master.csv to plant_master.csv

In [8]:
df = spark.read.csv(
"manufacturing_production_120k.csv",
header=True,
inferSchema=True
)

In [9]:
df.show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|
|    PR0000011|     2026-09-29|    PL03|     MC012|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|
|    PR0000012|     2026-07-10|    PL06|     MC030|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|
|    PR0000013|     2026-07-19|    PL06|     MC027|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|
|    PR0000014|     2026-05-05|    PL03|     MC013|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|
|    PR0000015|     2026-03-15|    PL02|     MC007|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|
|    PR0000016|     2026-03-03|    PL04|     MC020|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|
|    PR0000018|     2026-01-30|    PL03|     MC012|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|
|    PR0000019|     2026-01-11|    PL01|     MC005|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|
|    PR0000020|     2026-02-18|    PL03|     MC014|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [10]:
df.printSchema()

root
 |-- production_id: string (nullable = true)
 |-- production_date: date (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- operator_id: string (nullable = true)
 |-- shift: string (nullable = true)
 |-- product_code: string (nullable = true)
 |-- product_family: string (nullable = true)
 |-- units_planned: integer (nullable = true)
 |-- units_produced: integer (nullable = true)
 |-- defective_units: integer (nullable = true)
 |-- downtime_minutes: integer (nullable = true)
 |-- energy_kwh: double (nullable = true)
 |-- temperature_c: double (nullable = true)
 |-- vibration_mm_s: double (nullable = true)
 |-- quality_status: string (nullable = true)
 |-- maintenance_flag: string (nullable = true)
 |-- supervisor: string (nullable = true)

In [11]:
print(df.columns)

['production_id', 'production_date', 'plant_id', 'machine_id', 'operator_id', 'shift', 'product_code', 'product_family', 'units_planned', 'units_produced', 'defective_units', 'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s', 'quality_status', 'maintenance_flag', 'supervisor']

In [12]:
print("Total records:", df.count())

Total records: 120000

In [13]:
df.select("production_id", "plant_id", "machine_id",
          "product_family", "units_produced").show()

+-------------+--------+----------+--------------+--------------+
|production_id|plant_id|machine_id|product_family|units_produced|
+-------------+--------+----------+--------------+--------------+
|    PR0000001|    PL03|     MC011|        Motors|           993|
|    PR0000002|    PL04|     MC019|   Controllers|           836|
|    PR0000003|    PL01|     MC002|        Motors|           380|
|    PR0000004|    PL03|     MC013|         Pumps|           720|
|    PR0000005|    PL04|     MC020|         Pumps|           296|
|    PR0000006|    PL01|     MC002|        Motors|           795|
|    PR0000007|    PL02|     MC007|        Valves|           955|
|    PR0000008|    PL02|     MC009|        Valves|           895|
|    PR0000009|    PL03|     MC015|   Controllers|           289|
|    PR0000010|    PL02|     MC006|   Controllers|           527|
|    PR0000011|    PL03|     MC012|         Pumps|           512|
|    PR0000012|    PL06|     MC030|   Controllers|           968|
|    PR0000013|    PL06|     MC027|   Controllers|           867|
|    PR0000014|    PL03|     MC013|        Valves|           456|
|    PR0000015|    PL02|     MC007|        Motors|          1042|
|    PR0000016|    PL04|     MC020|   Controllers|           732|
|    PR0000017|    PL03|     MC011|   Controllers|           963|
|    PR0000018|    PL03|     MC012|        Motors|           469|
|    PR0000019|    PL01|     MC005|        Valves|           380|
|    PR0000020|    PL03|     MC014|         Pumps|           573|
+-------------+--------+----------+--------------+--------------+
only showing top 20 rows

In [15]:
for field in df.schema.fields:
    print(field.name, field.dataType)

production_id StringType()
production_date DateType()
plant_id StringType()
machine_id StringType()
operator_id StringType()
shift StringType()
product_code StringType()
product_family StringType()
units_planned IntegerType()
units_produced IntegerType()
defective_units IntegerType()
downtime_minutes IntegerType()
energy_kwh DoubleType()
temperature_c DoubleType()
vibration_mm_s DoubleType()
quality_status StringType()
maintenance_flag StringType()
supervisor StringType()

In [17]:
from pyspark.sql import functions as F
df.orderBy(F.rand()).show()

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0108097|     2026-06-11|    PL01|     MC003|     OP0004|Evening|     PMP-310|         Pumps|         1008|           963|              0|              48|    190.77|        56.32|          2.26|          Pass|              No|    Bharat|
|    PR0032046|     2026-01-09|    PL02|     MC006|     OP0297|Morning|     CTL-130|   Controllers|          500|           494|             13|              26|    156.28|        47.68|          2.89|          Pass|              No|    Harini|
|    PR0075048|     2026-02-03|    PL03|     MC011|     OP0276|Morning|     VLV-220|        Valves|          359|           324|              3|               8|    122.99|        67.15|          4.87|          Pass|              No|     Anita|
|    PR0016136|     2026-05-24|    PL03|     MC012|     OP0038|Evening|     PMP-110|         Pumps|          770|           787|             16|               2|    261.32|        65.98|          4.19|          Pass|              No|     Anita|
|    PR0016074|     2026-10-07|    PL02|     MC010|     OP0354|Evening|     CTL-330|   Controllers|          669|           633|             23|               4|    167.51|        69.12|           1.6|          Pass|              No|    Bharat|
|    PR0066206|     2026-01-10|    PL05|     MC021|     OP0238|Morning|     MTR-300|        Motors|          407|           333|             16|              32|     60.39|        66.58|          3.78|        Rework|              No|     Farah|
|    PR0066809|     2026-05-22|    PL04|     MC017|     OP0500|Evening|     PMP-310|         Pumps|          670|           588|             11|               8|     192.1|        72.53|          2.72|          Pass|              No|     Gopal|
|    PR0066222|     2026-03-04|    PL04|     MC017|     OP0245|  Night|     CTL-130|   Controllers|          463|           454|              9|              17|    215.52|        65.08|          2.57|          Pass|              No|    Harini|
|    PR0114020|     2026-07-01|    PL05|     MC021|     OP0460|  Night|     VLV-320|        Valves|         1084|          1086|             27|              58|    522.95|        65.08|          2.68|          Pass|              No|     Farah|
|    PR0008399|     2026-02-16|    PL06|     MC026|     OP0387|Evening|     VLV-220|        Valves|          835|           698|             26|              25|    332.09|        50.41|          4.74|          Pass|              No|     Irfan|
|    PR0053855|     2026-04-20|    PL03|     MC014|     OP0543|Morning|     VLV-320|        Valves|         1162|          1079|             24|              52|    439.89|        68.64|          3.19|          Pass|              No|     Deepa|
|    PR0036011|     2026-02-08|    PL02|     MC007|     OP0288|Morning|     CTL-230|   Controllers|         1152|          1067|             43|              29|    472.97|        64.59|          2.64|          Pass|              No|    Charan|
|    PR0064399|     2026-01-19|    PL06|     MC029|     OP0495|Morning|     CTL-130|   Controllers|          732|           691|             10|             124|    304.42|        59.04|          3.68|        Reject|             Yes|     Irfan|
|    PR0030093|     2026-07-09|    PL05|     MC022|     OP0495|Morning|     MTR-300|        Motors|          258|           222|              3|              37|     55.46|        70.73|          4.88|        Reject|              No|     Deepa|
|    PR0063731|     2026-05-16|    PL01|     MC003|     OP0617|  Night|     MTR-100|        Motors|          837|           791|             23|              43|    339.19|        58.77|          4.19|          Pass|              No|     Anita|
|    PR0027215|     2026-04-14|    PL04|     MC018|     OP0099|Morning|     VLV-120|        Valves|          963|           928|             29|               0|    424.65|        72.15|          3.49|          Pass|              No|     Gopal|
|    PR0117133|     2026-03-19|    PL01|     MC005|     OP0356|Morning|     PMP-210|         Pumps|          495|           480|              0|             115|    238.49|        70.63|          3.86|          Pass|              No|     Farah|
|    PR0002210|     2026-06-03|    PL03|     MC014|     OP0169|Morning|     CTL-230|   Controllers|          712|           673|              0|               6|    273.91|        69.31|          1.24|          Pass|              No|    Harini|
|    PR0080562|     2026-05-16|    PL01|     MC003|     OP0126|Morning|     PMP-210|         Pumps|          573|           591|             34|              54|     289.3|        67.04|          2.53|        Reject|              No|     Irfan|
|    PR0032508|     2026-01-26|    PL04|     MC016|     OP0550|  Night|     MTR-200|        Motors|          439|           437|             12|               9|     183.1|        70.17|          3.62|          Pass|             Yes|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [18]:
plant_data = [
    ("PL01", "Hyderabad Plant", "Hyderabad"),
    ("PL02", "Pune Plant", "Pune"),
    ("PL03", "Chennai Plant", "Chennai"),
    ("PL04", "Bengaluru Plant", "Bengaluru"),
]

In [19]:
plant_cols = ["plant_id", "plant_name", "city"]
plant_small_df = spark.createDataFrame(plant_data, plant_cols)
plant_small_df.show()

+--------+---------------+---------+
|plant_id|     plant_name|     city|
+--------+---------------+---------+
|    PL01|Hyderabad Plant|Hyderabad|
|    PL02|     Pune Plant|     Pune|
|    PL03|  Chennai Plant|  Chennai|
|    PL04|Bengaluru Plant|Bengaluru|
+--------+---------------+---------+

In [20]:
plant_small_df.printSchema()

root
 |-- plant_id: string (nullable = true)
 |-- plant_name: string (nullable = true)
 |-- city: string (nullable = true)

In [23]:
from pyspark.sql.types import StructType, StructField, StringType

plant_schema = StructType([
    StructField("plant_id", StringType(), True),
    StructField("plant_name", StringType(), True),
    StructField("city", StringType(), True),
])
plant_schema_df = spark.createDataFrame(plant_data, schema=plant_schema)

In [24]:
plant_schema_df.printSchema()

root
 |-- plant_id: string (nullable = true)
 |-- plant_name: string (nullable = true)
 |-- city: string (nullable = true)

In [25]:
plant_schema_df = plant_schema_df.withColumn("country", F.lit("India"))
plant_schema_df.show()

+--------+---------------+---------+-------+
|plant_id|     plant_name|     city|country|
+--------+---------------+---------+-------+
|    PL01|Hyderabad Plant|Hyderabad|  India|
|    PL02|     Pune Plant|     Pune|  India|
|    PL03|  Chennai Plant|  Chennai|  India|
|    PL04|Bengaluru Plant|Bengaluru|  India|
+--------+---------------+---------+-------+

In [27]:
import pandas as pd
pdf = pd.read_csv("manufacturing_production_120k.csv")

In [28]:
display(pdf.head(5))

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [29]:
display(pdf.tail(5))

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
119995,PR0119996,2026-07-13,PL05,MC022,OP0193,Evening,MTR-200,Motors,435,399,1,73.0,126.07,62.79,5.73,Rework,No,Bharat
119996,PR0119997,2026-04-26,PL05,MC024,OP0124,Evening,CTL-130,Controllers,813,777,8,49.0,318.22,63.05,3.53,Pass,No,Irfan
119997,PR0119998,2026-02-01,PL06,MC027,OP0051,Evening,VLV-120,Valves,650,597,13,0.0,269.46,60.52,3.81,Pass,No,Bharat
119998,PR0119999,2026-01-17,PL01,MC001,OP0452,Evening,MTR-300,Motors,887,899,22,21.0,184.62,64.89,5.20,Pass,Yes,Farah
119999,PR0120000,2026-08-16,PL02,MC007,OP0420,Morning,MTR-200,Motors,547,477,4,43.0,107.95,62.50,3.97,Pass,No,Farah

In [30]:
print("Shape:", pdf.shape)

Shape: (120000, 18)

In [31]:
print(pdf.columns.tolist())

['production_id', 'production_date', 'plant_id', 'machine_id', 'operator_id', 'shift', 'product_code', 'product_family', 'units_planned', 'units_produced', 'defective_units', 'downtime_minutes', 'energy_kwh', 'temperature_c', 'vibration_mm_s', 'quality_status', 'maintenance_flag', 'supervisor']

In [32]:
print(pdf.dtypes)

production_id        object
production_date      object
plant_id             object
machine_id           object
operator_id          object
shift                object
product_code         object
product_family       object
units_planned         int64
units_produced        int64
defective_units       int64
downtime_minutes    float64
energy_kwh          float64
temperature_c       float64
vibration_mm_s      float64
quality_status       object
maintenance_flag     object
supervisor           object
dtype: object

In [33]:
display(pdf[["plant_id", "machine_id", "units_produced"]].head())

  plant_id machine_id  units_produced
0     PL03      MC011             993
1     PL04      MC019             836
2     PL01      MC002             380
3     PL03      MC013             720
4     PL04      MC020             296

In [34]:
pdf_renamed = pdf.rename(columns={"units_produced": "production_output"})
display(pdf_renamed.head())

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,production_output,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [35]:
display(pdf[pdf["quality_status"] == "Reject"].head())

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
7,PR0000008,2026-08-17,PL02,MC009,OP0106,Night,VLV-320,Valves,862,895,51,77.0,266.06,57.10,1.34,Reject,No,Irfan
9,PR0000010,2026-02-13,PL02,MC006,OP0593,Evening,CTL-230,Controllers,532,527,26,64.0,112.17,60.96,3.48,Reject,No,Gopal
21,PR0000022,2026-03-03,PL02,MC009,OP0294,Evening,MTR-300,Motors,623,560,23,14.0,217.69,55.23,3.28,Reject,Yes,Farah

In [36]:
display(pdf[pdf["temperature_c"] > 75].head())

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
14,PR0000015,2026-03-15,PL02,MC007,OP0238,Morning,MTR-300,Motors,1086,1042,4,172.0,239.64,76.39,2.81,Pass,No,Deepa
16,PR0000017,2026-08-04,PL03,MC011,OP0533,Morning,CTL-330,Controllers,1152,963,28,91.0,347.34,75.09,4.00,Pass,Yes,Gopal
19,PR0000020,2026-02-18,PL03,MC014,OP0563,Morning,PMP-310,Pumps,646,573,13,64.0,277.73,76.92,2.35,Pass,No,Irfan
26,PR0000027,2026-01-03,PL05,MC023,OP0190,Morning,PMP-210,Pumps,358,310,6,46.0,78.29,75.42,3.72,Rework,No,Anita
54,PR0000055,2026-07-31,PL01,MC005,OP0212,Morning,CTL-230,Controllers,499,478,10,32.0,112.60,75.10,3.38,Pass,No,Farah

In [38]:
plant_pdf = pd.read_csv("plant_master.csv")
pdf_with_plant = pdf.merge(plant_pdf[["plant_id", "city"]], on="plant_id", how="left")
display(pdf_with_plant[
    (pdf_with_plant["shift"] == "Night") &
    (pdf_with_plant["city"].str.lower() == "hyderabad")
].head())

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor,city
29,PR0000030,2026-09-18,PL01,MC004,OP0266,Night,VLV-320,Valves,358,359,1,19.0,107.98,72.00,1.73,Pass,No,Bharat,Hyderabad
38,PR0000039,2026-07-17,PL01,MC002,OP0220,Night,VLV-120,Valves,260,265,0,2.0,127.18,51.87,3.41,Pass,No,Irfan,Hyderabad
62,PR0000063,2026-02-18,PL01,MC002,OP0390,Night,VLV-120,Valves,656,665,0,44.0,311.80,58.34,2.00,Pass,No,Deepa,Hyderabad
79,PR0000080,2026-06-10,PL01,MC003,OP0214,Night,CTL-130,Controllers,948,821,49,20.0,188.65,62.68,2.85,Reject,No,Anita,Hyderabad
145,PR0000146,2026-08-19,PL01,MC005,OP0088,Night,VLV-120,Valves,1156,969,0,9.0,501.65,67.41,5.76,Rework,No,Bharat,Hyderabad

In [40]:
%pip -q install "dask[dataframe]"

In [43]:
import dask.dataframe as dd
ddf = dd.read_csv("manufacturing_production_120k.csv")

In [45]:
ddf = dd.read_csv("manufacturing_production_120k.csv", dtype={'downtime_minutes': 'float64'})
display(ddf.head())

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
0,PR0000001,2026-08-07,PL03,MC011,OP0275,Evening,MTR-100,Motors,1060,993,30,34.0,388.11,61.40,3.88,Rework,No,Charan
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
3,PR0000004,2026-01-15,PL03,MC013,OP0076,Morning,PMP-210,Pumps,787,720,7,39.0,217.61,64.47,NaN,Rework,No,Farah
4,PR0000005,2026-09-21,PL04,MC020,OP0501,Morning,PMP-110,Pumps,344,296,7,49.0,115.47,72.59,3.21,Pass,No,Deepa

In [46]:
print("Partitions:", ddf.npartitions)

Partitions: 1

In [47]:
display(ddf[["plant_id", "product_family", "units_produced"]].head())

  plant_id product_family  units_produced
0     PL03         Motors             993
1     PL04    Controllers             836
2     PL01         Motors             380
3     PL03          Pumps             720
4     PL04          Pumps             296

In [48]:
rejected_ddf = ddf[ddf["quality_status"] == "Reject"]
display(rejected_ddf.head())

,production_id,production_date,plant_id,machine_id,operator_id,shift,product_code,product_family,units_planned,units_produced,defective_units,downtime_minutes,energy_kwh,temperature_c,vibration_mm_s,quality_status,maintenance_flag,supervisor
1,PR0000002,2026-08-03,PL04,MC019,OP0489,Morning,CTL-330,Controllers,809,836,0,0.0,398.58,64.37,2.28,Reject,No,Farah
2,PR0000003,2026-05-20,PL01,MC002,OP0189,Evening,MTR-300,Motors,442,380,17,15.0,183.34,54.13,4.66,Reject,No,Deepa
7,PR0000008,2026-08-17,PL02,MC009,OP0106,Night,VLV-320,Valves,862,895,51,77.0,266.06,57.10,1.34,Reject,No,Irfan
9,PR0000010,2026-02-13,PL02,MC006,OP0593,Evening,CTL-230,Controllers,532,527,26,64.0,112.17,60.96,3.48,Reject,No,Gopal
21,PR0000022,2026-03-03,PL02,MC009,OP0294,Evening,MTR-300,Motors,623,560,23,14.0,217.69,55.23,3.28,Reject,Yes,Farah

In [193]:
avg_by_plant = ddf.groupby("plant_id")["units_produced"].mean().compute()
display(avg_by_plant)

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

In [194]:
defects_by_family = ddf.groupby("product_family")["defective_units"].sum().compute()
display(defects_by_family)

product_family
Controllers    507781
Motors         505287
Pumps          507864
Valves         509312
Name: defective_units, dtype: int64

In [195]:
pandas_avg_by_plant = pdf.groupby("plant_id")["units_produced"].mean()
display(pandas_avg_by_plant)
print("Dask and Pandas average by plant:")
display(pd.concat(
    [pandas_avg_by_plant.rename("pandas_average"),
     avg_by_plant.rename("dask_average")],
    axis=1
))

plant_id
PL01    672.998304
PL02    672.781326
PL03    675.665503
PL04    673.835101
PL05    673.124994
PL06    678.006884
Name: units_produced, dtype: float64

Dask and Pandas average by plant:

          pandas_average  dask_average
plant_id
PL01          672.998304    672.998304
PL02          672.781326    672.781326
PL03          675.665503    675.665503
PL04          673.835101    673.835101
PL05          673.124994    673.124994
PL06          678.006884    678.006884

In [57]:
df_transformed = df.withColumn(
    "production_efficiency",
    F.when(F.col("units_planned") != 0,
           F.col("units_produced") / F.col("units_planned") * 100)
)

In [58]:
df_transformed = df_transformed.withColumn(
    "good_units", F.col("units_produced") - F.col("defective_units")
)

In [59]:
df_transformed = df_transformed.withColumn("country", F.lit("India"))

In [60]:
df_transformed = df_transformed.withColumnRenamed("energy_kwh", "energy_consumed")

In [61]:
df_transformed = df_transformed.withColumn(
    "units_produced", F.col("units_produced").cast("double")
)

In [62]:
df_transformed = df_transformed.withColumn(
    "defect_percentage",
    F.when(F.col("units_produced") != 0,
           F.col("defective_units") / F.col("units_produced") * 100)
)

In [63]:
df_transformed = df_transformed.withColumn(
    "energy_per_unit",
    F.when(F.col("units_produced") != 0,
           F.col("energy_consumed") / F.col("units_produced"))
)

In [64]:
df_transformed.select(
    "production_id", "units_produced", "units_planned",
    "production_efficiency", "good_units", "country",
    "energy_consumed", "defect_percentage", "energy_per_unit"
).show(20, truncate=False)

+-------------+--------------+-------------+---------------------+----------+-------+---------------+------------------+-------------------+
|production_id|units_produced|units_planned|production_efficiency|good_units|country|energy_consumed|defect_percentage |energy_per_unit    |
+-------------+--------------+-------------+---------------------+----------+-------+---------------+------------------+-------------------+
|PR0000001    |993.0         |1060         |93.67924528301886    |963       |India  |388.11         |3.0211480362537766|0.39084592145015107|
|PR0000002    |836.0         |809          |103.33745364647713   |836       |India  |398.58         |0.0               |0.4767703349282296 |
|PR0000003    |380.0         |442          |85.97285067873304    |363       |India  |183.34         |4.473684210526316 |0.48247368421052633|
|PR0000004    |720.0         |787          |91.4866581956798     |713       |India  |217.61         |0.9722222222222222|0.30223611111111115|
|PR0000005    |296.0         |344          |86.04651162790698    |289       |India  |115.47         |2.364864864864865 |0.3901013513513513 |
|PR0000006    |795.0         |958          |82.98538622129436    |745       |India  |290.26         |6.289308176100629 |0.3651069182389937 |
|PR0000007    |955.0         |1165         |81.97424892703863    |945       |India  |355.56         |1.0471204188481675|0.37231413612565445|
|PR0000008    |895.0         |862          |103.82830626450117   |844       |India  |266.06         |5.698324022346369 |0.2972737430167598 |
|PR0000009    |289.0         |313          |92.33226837060703    |281       |India  |87.62          |2.768166089965398 |0.3031833910034602 |
|PR0000010    |527.0         |532          |99.06015037593986    |501       |India  |112.17         |4.933586337760911 |0.2128462998102467 |
|PR0000011    |512.0         |577          |88.73483535528595    |498       |India  |127.0          |2.734375          |0.248046875        |
|PR0000012    |968.0         |980          |98.77551020408163    |945       |India  |377.97         |2.37603305785124  |0.3904648760330579 |
|PR0000013    |867.0         |1004         |86.35458167330677    |840       |India  |388.61         |3.1141868512110724|0.4482237600922722 |
|PR0000014    |456.0         |448          |101.78571428571428   |450       |India  |108.83         |1.3157894736842104|0.23866228070175438|
|PR0000015    |1042.0        |1086         |95.94843462246777    |1038      |India  |239.64         |0.3838771593090211|0.22998080614203453|
|PR0000016    |732.0         |870          |84.13793103448276    |732       |India  |289.55         |0.0               |0.3955601092896175 |
|PR0000017    |963.0         |1152         |83.59375             |935       |India  |347.34         |2.907580477673936 |0.36068535825545167|
|PR0000018    |469.0         |541          |86.69131238447319    |451       |India  |241.05         |3.8379530916844353|0.5139658848614073 |
|PR0000019    |380.0         |381          |99.73753280839895    |364       |India  |137.99         |4.2105263157894735|0.36313157894736847|
|PR0000020    |573.0         |646          |88.69969040247679    |560       |India  |277.73         |2.2687609075043627|0.484694589877836  |
+-------------+--------------+-------------+---------------------+----------+-------+---------------+------------------+-------------------+
only showing top 20 rows

In [65]:
df.drop("supervisor").show(5)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+
only showing top 5 rows

In [66]:
df.drop("supervisor", "maintenance_flag").show(5)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+
only showing top 5 rows

In [67]:
df_no_duplicates = df.dropDuplicates()
print("Rows after dropping exact duplicates:", df_no_duplicates.count())

Rows after dropping exact duplicates: 120000

In [68]:
df_one_per_production = df.dropDuplicates(["production_id"])
print("Unique production IDs:", df_one_per_production.count())

Unique production IDs: 120000

In [69]:
df_operator_present = df.filter(
    F.col("operator_id").isNotNull() & (F.trim(F.col("operator_id")) != "")
)
print("Rows with operator ID:", df_operator_present.count())

Rows with operator ID: 118476

In [70]:
df_sensor_present = df.filter(
    ~(F.col("temperature_c").isNull() & F.col("vibration_mm_s").isNull())
)
print("Rows where both sensor values are not missing:", df_sensor_present.count())

Rows where both sensor values are not missing: 119963

In [71]:
df.select("product_family").distinct().show()

+--------------+
|product_family|
+--------------+
|         Pumps|
|        Valves|
|   Controllers|
|        Motors|
+--------------+

In [72]:
df.select("plant_id", "machine_id").distinct().show()

+--------+----------+
|plant_id|machine_id|
+--------+----------+
|    PL01|     MC001|
|    PL01|     MC004|
|    PL04|     MC019|
|    PL04|     MC017|
|    PL05|     MC022|
|    PL04|     MC018|
|    PL01|     MC003|
|    PL06|     MC029|
|    PL02|     MC007|
|    PL03|     MC013|
|    PL06|     MC030|
|    PL04|     MC020|
|    PL05|     MC021|
|    PL01|     MC005|
|    PL02|     MC010|
|    PL04|     MC016|
|    PL06|     MC027|
|    PL02|     MC006|
|    PL01|     MC002|
|    PL06|     MC028|
+--------+----------+
only showing top 20 rows

In [73]:
df.orderBy(F.col("units_produced").asc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0038643|     2026-08-06|    PL02|     MC009|     OP0361|Evening|     MTR-100|        Motors|          250|           205|              6|              73|     65.18|        55.99|          2.72|          Pass|              No|    Harini|
|    PR0059668|     2026-05-01|    PL05|     MC021|     OP0067|  Night|     CTL-130|   Controllers|          250|           205|             11|              54|     89.67|        58.31|          2.69|          Pass|              No|     Anita|
|    PR0079337|     2026-05-05|    PL04|     MC018|     OP0623|Evening|     PMP-210|         Pumps|          251|           206|              0|               0|     77.66|        67.78|          2.36|        Rework|              No|     Irfan|
|    PR0013719|     2026-04-30|    PL03|     MC014|     OP0340|Morning|     MTR-200|        Motors|          250|           206|              5|              82|     62.29|        55.57|           2.4|          Pass|              No|    Harini|
|    PR0087182|     2026-09-03|    PL04|     MC019|     OP0196|Evening|     CTL-330|   Controllers|          250|           206|              4|              13|     98.25|        59.27|          6.99|        Reject|             Yes|     Irfan|
|    PR0015709|     2026-03-09|    PL05|     MC021|     OP0538|  Night|     VLV-220|        Valves|          251|           206|              9|               3|     87.29|        68.35|          1.27|        Reject|              No|    Bharat|
|    PR0115075|     2026-10-03|    PL04|     MC019|     OP0014|  Night|     CTL-130|   Controllers|          251|           206|              1|              66|     79.31|         78.2|          4.21|        Rework|              No|    Bharat|
|    PR0026161|     2026-04-28|    PL05|     MC025|     OP0617|Evening|     PMP-210|         Pumps|          251|           206|              2|              42|     74.72|        76.08|          3.96|        Reject|             Yes|     Gopal|
|    PR0030899|     2026-05-24|    PL01|     MC004|     OP0380|Evening|     VLV-120|        Valves|          252|           206|             12|              12|     75.94|        50.77|          3.34|        Rework|              No|     Farah|
|    PR0039880|     2026-01-04|    PL01|     MC005|     OP0034|Evening|     PMP-210|         Pumps|          250|           206|              0|              38|      50.0|        64.38|          2.33|        Rework|              No|     Deepa|
|    PR0071924|     2026-05-26|    PL01|     MC003|     OP0120|  Night|     PMP-210|         Pumps|          251|           206|              9|              40|      50.0|        52.13|          2.54|          Pass|              No|     Irfan|
|    PR0107410|     2026-09-29|    PL03|     MC012|     OP0237|Evening|     VLV-120|        Valves|          252|           207|              8|              36|     99.97|        61.39|          3.94|          Pass|              No|     Deepa|
|    PR0013195|     2026-03-18|    PL05|     MC021|     OP0182|  Night|     PMP-310|         Pumps|          253|           207|              4|              18|     59.88|        73.69|          2.98|          Pass|              No|     Irfan|
|    PR0118888|     2026-06-01|    PL04|     MC019|     OP0350|Morning|     MTR-300|        Motors|          250|           207|              3|              29|      50.0|        53.55|          4.18|          Pass|              No|     Farah|
|    PR0020293|     2026-08-08|    PL03|     MC014|     OP0567|Evening|     CTL-130|   Controllers|          253|           207|              5|              37|      50.0|        64.89|          1.81|          Pass|              No|     Deepa|
|    PR0028542|     2026-04-10|    PL04|     MC020|     OP0325|Evening|     CTL-230|   Controllers|          251|           207|              8|              18|     93.84|         64.9|          1.55|          Pass|              No|     Anita|
|    PR0035230|     2026-02-05|    PL06|     MC029|     OP0479|  Night|     VLV-120|        Valves|          253|           207|              6|               0|    107.62|         NULL|          3.56|        Rework|              No|     Anita|
|    PR0097162|     2026-09-02|    PL06|     MC027|     OP0139|  Night|     MTR-100|        Motors|          252|           208|              6|              11|     92.62|        61.86|          1.74|          Pass|              No|     Deepa|
|    PR0005895|     2026-09-15|    PL04|     MC018|     OP0322|  Night|     VLV-320|        Valves|          251|           208|              3|              33|     66.87|        49.32|          2.91|          Pass|              No|    Bharat|
|    PR0105232|     2026-08-26|    PL04|     MC018|     OP0505|Evening|     VLV-220|        Valves|          251|           208|              8|               0|      59.1|        57.55|          3.65|          Pass|              No|     Irfan|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [74]:
df.orderBy(F.col("units_produced").desc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [75]:
df.orderBy(F.col("defective_units").desc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0051359|     2026-09-16|    PL02|     MC009|     OP0181|Morning|     CTL-230|   Controllers|         1192|          1230|            108|               8|    555.34|        71.97|          2.09|        Rework|              No|     Irfan|
|    PR0108009|     2026-06-07|    PL05|     MC023|     OP0417|Morning|     CTL-230|   Controllers|         1061|          1067|            106|               0|    491.74|         NULL|          4.93|        Rework|             Yes|     Farah|
|    PR0067365|     2026-05-13|    PL01|     MC001|     OP0461|Evening|     MTR-100|        Motors|         1189|          1186|            103|               0|    373.15|        64.44|          4.27|        Reject|             Yes|     Farah|
|    PR0070440|     2026-05-23|    PL04|     MC018|     OP0033|  Night|     VLV-120|        Valves|         1133|          1124|            102|               0|    238.46|        71.28|          2.79|        Reject|              No|     Deepa|
|    PR0082514|     2026-03-18|    PL04|     MC017|     OP0007|Morning|     PMP-310|         Pumps|         1181|          1109|            100|              19|    331.99|        56.53|          2.97|        Reject|              No|     Anita|
|    PR0106744|     2026-04-27|    PL01|     MC003|     OP0094|Evening|     CTL-130|   Controllers|         1084|          1103|            100|               0|    465.02|        68.15|          2.18|        Rework|              No|    Charan|
|    PR0013103|     2026-05-06|    PL02|     MC009|     OP0159|Morning|     MTR-100|        Motors|         1042|           990|             97|              30|    196.72|        57.62|          3.46|        Rework|              No|    Harini|
|    PR0045241|     2026-01-04|    PL03|     MC013|     OP0202|Morning|     VLV-320|        Valves|         1197|          1231|             96|              23|    456.16|         63.5|          1.55|        Rework|              No|    Harini|
|    PR0103867|     2026-06-07|    PL04|     MC017|     OP0033|Morning|     PMP-310|         Pumps|         1088|          1095|             95|              29|    411.22|        62.63|           0.4|        Rework|              No|     Irfan|
|    PR0043427|     2026-02-04|    PL04|     MC017|     OP0003|Morning|     VLV-120|        Valves|         1170|          1196|             95|              19|    218.83|        65.99|          NULL|        Rework|              No|     Deepa|
|    PR0068424|     2026-07-18|    PL06|     MC027|     OP0609|Evening|     VLV-320|        Valves|         1052|          1073|             93|              52|    406.85|         57.3|          4.71|        Reject|             Yes|    Harini|
|    PR0014350|     2026-09-27|    PL05|     MC023|     OP0458|Evening|     CTL-330|   Controllers|         1120|          1128|             91|               7|    250.83|        61.73|          4.66|        Rework|              No|     Farah|
|    PR0068990|     2026-02-02|    PL01|     MC004|     OP0210|Evening|     CTL-230|   Controllers|         1136|          1104|             91|              47|    232.35|        61.59|          3.57|        Reject|              No|     Farah|
|    PR0078536|     2026-05-11|    PL03|     MC012|     OP0486|  Night|     PMP-110|         Pumps|         1141|          1095|             91|              51|    301.78|        62.09|          3.48|        Rework|              No|     Farah|
|    PR0039878|     2026-07-28|    PL05|     MC022|     OP0464|Evening|     MTR-100|        Motors|         1052|           990|             90|              14|    341.79|        57.54|           3.7|        Reject|              No|    Charan|
|    PR0082255|     2026-09-01|    PL02|     MC007|     OP0528|  Night|     VLV-320|        Valves|         1174|          1123|             89|              20|    314.99|        71.07|          0.83|        Rework|              No|     Gopal|
|    PR0085319|     2026-09-23|    PL05|     MC024|     OP0399|Morning|     VLV-120|        Valves|          973|           970|             89|              52|    390.03|         59.4|          1.64|        Rework|             Yes|     Irfan|
|    PR0027472|     2026-10-22|    PL04|     MC016|     OP0340|Morning|     CTL-330|   Controllers|         1100|           960|             88|              40|    341.48|        51.33|          4.22|        Rework|              No|    Harini|
|    PR0116375|     2026-01-06|    PL03|     MC015|     OP0318|  Night|     MTR-200|        Motors|         1174|          1206|             88|              68|    405.22|        57.62|          4.43|        Rework|              No|     Farah|
|    PR0064147|     2026-07-28|    PL01|     MC004|     OP0105|Evening|     MTR-100|        Motors|         1162|          1159|             88|               0|    297.53|        58.15|           0.4|        Rework|              No|     Gopal|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [76]:
df.orderBy(F.col("plant_id").asc(), F.col("units_produced").desc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|
|    PR0006350|     2026-02-04|    PL01|     MC004|     OP0322|  Night|     PMP-110|         Pumps|         1193|          1234|             38|              27|    585.43|        59.48|          2.58|          Pass|             Yes|     Anita|
|    PR0046906|     2026-04-21|    PL01|     MC005|     OP0649|Evening|     CTL-230|   Controllers|         1199|          1233|             75|              42|    392.44|        69.03|          2.04|        Reject|             Yes|     Gopal|
|    PR0046582|     2026-07-18|    PL01|     MC002|     OP0040|  Night|     MTR-100|        Motors|         1190|          1230|              3|              34|    232.68|        51.69|          4.69|        Reject|              No|     Irfan|
|    PR0097172|     2026-01-29|    PL01|     MC002|     OP0257|  Night|     PMP-310|         Pumps|         1198|          1229|             55|              30|    444.46|        71.27|          4.99|        Rework|              No|     Deepa|
|    PR0024941|     2026-04-21|    PL01|     MC002|     OP0101|Evening|     VLV-120|        Valves|         1193|          1229|             25|             117|    310.61|        65.69|          2.64|        Reject|              No|    Harini|
|    PR0088933|     2026-03-04|    PL01|     MC003|     OP0492|Morning|     MTR-300|        Motors|         1190|          1229|             51|              34|    267.82|        78.75|          4.76|        Rework|              No|    Bharat|
|    PR0048075|     2026-03-05|    PL01|     MC005|     OP0171|Evening|     PMP-310|         Pumps|         1196|          1228|             14|              12|    569.62|        54.97|          4.02|          Pass|              No|    Harini|
|    PR0083644|     2026-07-13|    PL01|     MC005|     OP0043|Evening|     PMP-310|         Pumps|         1188|          1228|             16|              30|    533.46|        70.21|          4.53|          Pass|              No|    Bharat|
|    PR0002284|     2026-08-31|    PL01|     MC004|     OP0639|Evening|     PMP-110|         Pumps|         1192|          1227|             30|               0|    438.15|        66.08|          3.65|        Rework|              No|     Farah|
|    PR0109962|     2026-03-06|    PL01|     MC001|     OP0536|Evening|     MTR-300|        Motors|         1199|          1227|             16|              15|    280.96|        52.32|          2.04|          Pass|              No|     Gopal|
|    PR0012821|     2026-07-14|    PL01|     MC005|     OP0195|Morning|     CTL-130|   Controllers|         1192|          1226|              7|              58|     625.8|        57.83|          2.22|        Reject|              No|     Farah|
|    PR0119269|     2026-06-22|    PL01|     MC005|     OP0125|Evening|     MTR-200|        Motors|         1182|          1226|             21|              33|    268.92|        67.94|          2.68|        Reject|              No|     Farah|
|    PR0000300|     2026-05-07|    PL01|     MC003|     OP0478|Evening|     VLV-320|        Valves|         1181|          1226|             31|              35|    359.21|         69.8|          3.13|        Reject|              No|     Farah|
|    PR0083683|     2026-04-10|    PL01|     MC002|     OP0268|Evening|     MTR-200|        Motors|         1188|          1226|             16|              45|    455.05|        59.46|          3.55|          Pass|              No|     Anita|
|    PR0022084|     2026-01-26|    PL01|     MC004|     OP0396|Morning|     PMP-310|         Pumps|         1198|          1226|             38|              15|    617.55|        69.97|          3.97|        Reject|             Yes|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [78]:
df.orderBy(F.col("units_produced").desc()).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|
|    PR0098449|     2026-08-11|    PL05|     MC022|     OP0049|Morning|     PMP-110|         Pumps|         1198|          1238|             58|              47|    600.77|        63.45|          3.29|          Pass|              No|     Irfan|
|    PR0074297|     2026-05-20|    PL04|     MC019|     OP0142|Morning|     MTR-200|        Motors|         1195|          1238|             23|               0|     331.2|        66.75|           4.1|          Pass|              No|     Deepa|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 20 rows

In [79]:
df.orderBy(F.col("downtime_minutes").desc_nulls_last()).show(10)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|    PR0092818|     2026-02-16|    PL06|     MC027|     OP0016|Morning|     PMP-210|         Pumps|         1066|           907|              2|             281|    359.48|        54.03|           2.8|          Pass|              No|     Farah|
|    PR0045363|     2026-07-07|    PL02|     MC010|     OP0215|  Night|     CTL-330|   Controllers|          502|           463|              3|             278|    112.25|        72.69|          4.03|          Pass|              No|    Bharat|
|    PR0020842|     2026-04-28|    PL02|     MC008|     OP0003|  Night|     MTR-200|        Motors|         1004|           985|             24|             267|    326.53|        53.78|          3.82|        Reject|              No|    Harini|
|    PR0065023|     2026-02-11|    PL06|     MC029|     OP0249|Evening|     CTL-230|   Controllers|          708|           654|             23|             267|    220.98|         67.8|           4.8|          Pass|              No|     Deepa|
|    PR0068768|     2026-03-27|    PL03|     MC012|     OP0098|  Night|     MTR-200|        Motors|          958|           898|             15|             267|     172.3|        64.62|          4.59|          Pass|              No|     Farah|
|    PR0100950|     2026-01-16|    PL03|     MC012|     OP0076|Evening|     MTR-100|        Motors|          977|           900|             13|             263|     401.3|        66.18|          1.91|          Pass|              No|    Charan|
|    PR0041129|     2026-02-06|    PL01|     MC005|     OP0338|Morning|     PMP-110|         Pumps|          374|           361|              6|             263|    158.25|        71.94|          3.47|          Pass|              No|     Gopal|
|    PR0049997|     2026-08-30|    PL04|     MC019|     OP0337|  Night|     PMP-310|         Pumps|          584|           575|              7|             263|    292.82|        42.51|          5.13|          Pass|             Yes|     Farah|
|    PR0022495|     2026-06-18|    PL05|     MC022|     OP0619|Evening|     VLV-120|        Valves|         1172|          1141|             56|             262|     265.5|        53.16|          4.48|          Pass|              No|    Charan|
|    PR0112855|     2026-03-28|    PL02|     MC008|     OP0589|Morning|     MTR-100|        Motors|          319|           269|              2|             261|     92.92|         69.9|          2.57|          Pass|             Yes|    Harini|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
only showing top 10 rows

In [80]:
df.groupBy("machine_id").agg(
    F.max("vibration_mm_s").alias("highest_vibration")
).orderBy(F.col("highest_vibration").desc_nulls_last()).show(20)

+----------+-----------------+
|machine_id|highest_vibration|
+----------+-----------------+
|     MC012|             8.56|
|     MC030|             8.25|
|     MC027|             7.85|
|     MC010|              7.8|
|     MC018|             7.79|
|     MC024|             7.77|
|     MC015|             7.76|
|     MC016|             7.63|
|     MC007|             7.61|
|     MC017|             7.52|
|     MC021|              7.5|
|     MC004|             7.48|
|     MC025|             7.46|
|     MC019|             7.45|
|     MC028|             7.43|
|     MC022|              7.4|
|     MC014|             7.37|
|     MC006|             7.36|
|     MC008|             7.32|
|     MC023|             7.29|
+----------+-----------------+
only showing top 20 rows

In [81]:
df.agg(
    F.sum("units_planned").alias("total_units_planned"),
    F.sum("units_produced").alias("total_units_produced"),
    F.sum("defective_units").alias("total_defective_units"),
    F.avg("units_produced").alias("average_units_produced"),
    F.max("units_produced").alias("maximum_production_output"),
    F.min("units_produced").alias("minimum_production_output"),
    F.avg("downtime_minutes").alias("average_downtime_minutes"),
    F.sum("energy_kwh").alias("total_energy_consumed"),
    F.avg("temperature_c").alias("average_temperature"),
    F.avg("vibration_mm_s").alias("average_vibration")
).show()

+-------------------+--------------------+---------------------+----------------------+-------------------------+-------------------------+------------------------+---------------------+-------------------+-----------------+
|total_units_planned|total_units_produced|total_defective_units|average_units_produced|maximum_production_output|minimum_production_output|average_downtime_minutes|total_energy_consumed|average_temperature|average_vibration|
+-------------------+--------------------+---------------------+----------------------+-------------------------+-------------------------+------------------------+---------------------+-------------------+-----------------+
|           87094621|            80927888|              2030244|     674.3990666666666|                     1245|                      205|       33.93149474428351| 2.8368014080000117E7| 63.021532392167266|3.398737691604917|
+-------------------+--------------------+---------------------+----------------------+-------------------------+-------------------------+------------------------+---------------------+-------------------+-----------------+

In [82]:
df.groupBy("plant_id").agg(F.sum("units_produced").alias("total_production")) \
  .orderBy(F.desc("total_production")).show()

+--------+----------------+
|plant_id|total_production|
+--------+----------------+
|    PL03|        13547769|
|    PL02|        13546452|
|    PL04|        13529935|
|    PL06|        13492337|
|    PL01|        13488232|
|    PL05|        13323163|
+--------+----------------+

In [83]:
df.groupBy("product_family").agg(F.sum("units_produced").alias("total_production")) \
  .orderBy(F.desc("total_production")).show()

+--------------+----------------+
|product_family|total_production|
+--------------+----------------+
|        Valves|        20433082|
|         Pumps|        20208739|
|   Controllers|        20168572|
|        Motors|        20117495|
+--------------+----------------+

In [84]:
df.groupBy("plant_id").agg(F.sum("defective_units").alias("total_defects")) \
  .orderBy(F.desc("total_defects")).show()

+--------+-------------+
|plant_id|total_defects|
+--------+-------------+
|    PL01|       339720|
|    PL02|       339647|
|    PL03|       339264|
|    PL06|       338993|
|    PL04|       338118|
|    PL05|       334502|
+--------+-------------+

In [85]:
df.groupBy("shift").agg(F.avg("downtime_minutes").alias("average_downtime")) \
  .orderBy(F.desc("average_downtime")).show()

+-------+------------------+
|  shift|  average_downtime|
+-------+------------------+
|Evening|  34.2213017151833|
|  Night|33.953058820580935|
|Morning| 33.61973080530278|
+-------+------------------+

In [86]:
df.groupBy("product_family").agg(F.avg("energy_kwh").alias("average_energy_kwh")) \
  .orderBy(F.desc("average_energy_kwh")).show()

+--------------+------------------+
|product_family|average_energy_kwh|
+--------------+------------------+
|        Motors|237.21818224597516|
|         Pumps|236.89137927582252|
|        Valves|236.34508750495314|
|   Controllers|235.15370433333288|
+--------------+------------------+

In [87]:
df.groupBy("quality_status").count().orderBy(F.desc("count")).show()

+--------------+-----+
|quality_status|count|
+--------------+-----+
|          Pass|74328|
|        Rework|22928|
|        Reject|22744|
+--------------+-----+

In [88]:
df.groupBy("plant_id", "shift").agg(F.sum("units_produced").alias("total_production")) \
  .orderBy("plant_id", F.desc("total_production")).show()

+--------+-------+----------------+
|plant_id|  shift|total_production|
+--------+-------+----------------+
|    PL01|  Night|         4562612|
|    PL01|Evening|         4477769|
|    PL01|Morning|         4447851|
|    PL02|Morning|         4561068|
|    PL02|  Night|         4558467|
|    PL02|Evening|         4426917|
|    PL03|  Night|         4599608|
|    PL03|Evening|         4487211|
|    PL03|Morning|         4460950|
|    PL04|Evening|         4540617|
|    PL04|Morning|         4497099|
|    PL04|  Night|         4492219|
|    PL05|Evening|         4475101|
|    PL05|Morning|         4431446|
|    PL05|  Night|         4416616|
|    PL06|  Night|         4604432|
|    PL06|Evening|         4458798|
|    PL06|Morning|         4429107|
+--------+-------+----------------+

In [89]:
df.groupBy("plant_id", "product_family").agg(F.sum("defective_units").alias("total_defects")) \
  .orderBy("plant_id", F.desc("total_defects")).show()

+--------+--------------+-------------+
|plant_id|product_family|total_defects|
+--------+--------------+-------------+
|    PL01|         Pumps|        87103|
|    PL01|        Valves|        84874|
|    PL01|        Motors|        84174|
|    PL01|   Controllers|        83569|
|    PL02|   Controllers|        87120|
|    PL02|        Motors|        84560|
|    PL02|         Pumps|        84491|
|    PL02|        Valves|        83476|
|    PL03|        Valves|        85333|
|    PL03|        Motors|        84926|
|    PL03|         Pumps|        84803|
|    PL03|   Controllers|        84202|
|    PL04|        Valves|        87084|
|    PL04|         Pumps|        83976|
|    PL04|        Motors|        83897|
|    PL04|   Controllers|        83161|
|    PL05|        Motors|        84331|
|    PL05|         Pumps|        83607|
|    PL05|   Controllers|        83589|
|    PL05|        Valves|        82975|
+--------+--------------+-------------+
only showing top 20 rows

In [90]:
df.groupBy("machine_id").agg(F.avg("temperature_c").alias("average_temperature")) \
  .orderBy(F.desc("average_temperature")).show()

+----------+-------------------+
|machine_id|average_temperature|
+----------+-------------------+
|     MC019| 63.266223444138944|
|     MC020|  63.22489208633087|
|     MC029|  63.13119731057668|
|     MC009|   63.1252779855396|
|     MC014| 63.114309957574186|
|     MC023| 63.109051746112684|
|     MC027| 63.099668282725126|
|     MC022|  63.09403431245128|
|     MC015|  63.09026488395557|
|     MC001|   63.0778733146782|
|     MC017|  63.07674442190667|
|     MC011| 63.060230414746606|
|     MC007|    63.037661716587|
|     MC016|  63.03639870582378|
|     MC026|  63.02672521957329|
|     MC021|  63.01464069491981|
|     MC005| 62.979236446933044|
|     MC028|  62.97779683034558|
|     MC030|  62.96733774497327|
|     MC024|  62.96457946271644|
+----------+-------------------+
only showing top 20 rows

In [91]:
df.groupBy("supervisor").agg(F.sum("units_produced").alias("total_output")) \
  .orderBy(F.desc("total_output")).show()

+----------+------------+
|supervisor|total_output|
+----------+------------+
|     Farah|    10276986|
|    Harini|    10215803|
|     Deepa|    10130817|
|    Bharat|    10122430|
|     Anita|    10089966|
|    Charan|    10037116|
|     Gopal|    10031531|
|     Irfan|    10023239|
+----------+------------+

In [92]:
plant_df = spark.read.csv(
"plant_master.csv",
header=True,
inferSchema=True
)

In [93]:
machine_df = spark.read.csv(
"machine_master.csv",
header=True,
inferSchema=True
)

In [94]:
production_plant = df.join(plant_df, on="plant_id", how="inner")

In [95]:
production_plant.select("production_id", "plant_name", "city",
                        "machine_id", "units_produced").show(20)

+-------------+---------------+---------+----------+--------------+
|production_id|     plant_name|     city|machine_id|units_produced|
+-------------+---------------+---------+----------+--------------+
|    PR0000001|  Chennai Plant|  Chennai|     MC011|           993|
|    PR0000002|    Noida Plant|    Noida|     MC019|           836|
|    PR0000003|Hyderabad Plant|Hyderabad|     MC002|           380|
|    PR0000004|  Chennai Plant|  Chennai|     MC013|           720|
|    PR0000005|    Noida Plant|    Noida|     MC020|           296|
|    PR0000006|Hyderabad Plant|Hyderabad|     MC002|           795|
|    PR0000007|     Pune Plant|     Pune|     MC007|           955|
|    PR0000008|     Pune Plant|     Pune|     MC009|           895|
|    PR0000009|  Chennai Plant|  Chennai|     MC015|           289|
|    PR0000010|     Pune Plant|     Pune|     MC006|           527|
|    PR0000011|  Chennai Plant|  Chennai|     MC012|           512|
|    PR0000012|  Kolkata Plant|  Kolkata|     MC030|           968|
|    PR0000013|  Kolkata Plant|  Kolkata|     MC027|           867|
|    PR0000014|  Chennai Plant|  Chennai|     MC013|           456|
|    PR0000015|     Pune Plant|     Pune|     MC007|          1042|
|    PR0000016|    Noida Plant|    Noida|     MC020|           732|
|    PR0000017|  Chennai Plant|  Chennai|     MC011|           963|
|    PR0000018|  Chennai Plant|  Chennai|     MC012|           469|
|    PR0000019|Hyderabad Plant|Hyderabad|     MC005|           380|
|    PR0000020|  Chennai Plant|  Chennai|     MC014|           573|
+-------------+---------------+---------+----------+--------------+
only showing top 20 rows

In [96]:
production_machine = df.join(
    machine_df, on=["machine_id", "plant_id"], how="inner"
)

In [97]:
production_all = df.join(plant_df, on="plant_id", how="left").join(
    machine_df, on=["machine_id", "plant_id"], how="left"
)
production_all.show(10)

+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+------------+-----------------+--------------+
|machine_id|plant_id|production_id|production_date|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|     plant_name|     city|region|year_opened|plant_manager|machine_type|capacity_per_hour|installed_year|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+------------+-----------------+--------------+
|     MC011|    PL03|    PR0000001|     2026-08-07|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|         CNC|              100|          2025|
|     MC019|    PL04|    PR0000002|     2026-08-03|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|    Noida Plant|    Noida| North|       2019|    M. Sharma|     Welding|               80|          2021|
|     MC002|    PL01|    PR0000003|     2026-05-20|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|    Assembly|               80|          2024|
|     MC013|    PL03|    PR0000004|     2026-01-15|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|     Casting|              180|          2020|
|     MC020|    PL04|    PR0000005|     2026-09-21|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|    Noida Plant|    Noida| North|       2019|    M. Sharma|     Testing|              120|          2018|
|     MC002|    PL01|    PR0000006|     2026-09-03|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|Hyderabad Plant|Hyderabad| South|       2016|     R. Menon|    Assembly|               80|          2024|
|     MC007|    PL02|    PR0000007|     2026-05-07|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|    Assembly|              100|          2022|
|     MC009|    PL02|    PR0000008|     2026-08-17|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|     Welding|               80|          2020|
|     MC015|    PL03|    PR0000009|     2026-03-10|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|  Chennai Plant|  Chennai| South|       2015| A. Natarajan|     Testing|              180|          2018|
|     MC006|    PL02|    PR0000010|     2026-02-13|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|     Pune Plant|     Pune|  West|       2018|  S. Kulkarni|         CNC|              100|          2021|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+---------------+---------+------+-----------+-------------+------------+-----------------+--------------+
only showing top 10 rows

In [98]:
production_plant.groupBy("city").agg(
    F.sum("units_produced").alias("total_production")
).orderBy(F.desc("total_production")).show()

+---------+----------------+
|     city|total_production|
+---------+----------------+
|  Chennai|        13547769|
|     Pune|        13546452|
|    Noida|        13529935|
|  Kolkata|        13492337|
|Hyderabad|        13488232|
|Ahmedabad|        13323163|
+---------+----------------+

In [99]:
production_machine.groupBy("machine_type").agg(
    F.avg("downtime_minutes").alias("average_downtime")
).orderBy(F.desc("average_downtime")).show()

+------------+-----------------+
|machine_type| average_downtime|
+------------+-----------------+
|     Casting| 34.1660783396419|
|     Welding|34.00449382099613|
|    Assembly|33.96718284443325|
|     Testing|33.87585594724829|
|         CNC|33.64548129466162|
+------------+-----------------+

In [100]:
production_plant.groupBy("region").agg(
    F.sum("defective_units").alias("total_defects")
).orderBy(F.desc("total_defects")).show()

+------+-------------+
|region|total_defects|
+------+-------------+
| South|       678984|
|  West|       674149|
|  East|       338993|
| North|       338118|
+------+-------------+

In [101]:
unmatched_machine = df.join(
    machine_df.select("machine_id", "plant_id"),
    on=["machine_id", "plant_id"], how="left_anti"
)
unmatched_machine.show(20)

+----------+--------+-------------+---------------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
|machine_id|plant_id|production_id|production_date|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|
+----------+--------+-------------+---------------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+
+----------+--------+-------------+---------------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+

In [102]:
left_join_check = df.join(
    machine_df.withColumnRenamed("machine_id", "master_machine_id"),
    df.machine_id == F.col("master_machine_id"),
    "left"
)
left_join_check.filter(F.col("master_machine_id").isNull()).show(20)

+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------+------------+-----------------+--------------+
|production_id|production_date|plant_id|machine_id|operator_id|shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|master_machine_id|plant_id|machine_type|capacity_per_hour|installed_year|
+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------+------------+-----------------+--------------+
+-------------+---------------+--------+----------+-----------+-----+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+-----------------+--------+------------+-----------------+--------------+

In [103]:
production_plant.groupBy("plant_name").agg(
    F.sum("energy_kwh").alias("total_energy_consumed")
).orderBy(F.desc("total_energy_consumed")).show()

+---------------+---------------------+
|     plant_name|total_energy_consumed|
+---------------+---------------------+
|     Pune Plant|    4757984.949999988|
|    Noida Plant|    4746238.580000002|
|  Chennai Plant|    4742748.169999995|
|Hyderabad Plant|    4725471.189999996|
|  Kolkata Plant|    4723180.160000009|
|Ahmedabad Plant|     4672391.03000001|
+---------------+---------------------+

In [104]:
df_updated = df.withColumn(
    "quality_status",
    F.when(F.col("quality_status") == "Reject", "Failed")
     .otherwise(F.col("quality_status"))
)

In [105]:
df_updated = df_updated.withColumn(
    "quality_status",
    F.when(F.col("quality_status") == "Rework", "Requires Review")
     .otherwise(F.col("quality_status"))
)

In [106]:
df_updated = df_updated.withColumn(
    "units_planned",
    F.when(F.col("product_family") == "Motors", F.col("units_planned") * 1.05)
     .otherwise(F.col("units_planned"))
)

In [107]:
df_updated = df_updated.withColumn(
    "energy_kwh",
    F.when(F.col("shift") == "Night", F.col("energy_kwh") * 1.03)
     .otherwise(F.col("energy_kwh"))
)

In [108]:
df_updated = df_updated.withColumn(
    "operator_id",
    F.when(F.col("operator_id").isNull() | (F.trim(F.col("operator_id")) == ""),
           "UNASSIGNED").otherwise(F.col("operator_id"))
)

In [109]:
df_updated = df_updated.withColumn(
    "supervisor",
    F.when(F.col("supervisor") == "Anita", "Anita Rao")
     .otherwise(F.col("supervisor"))
)

In [110]:
average_temperature = df.agg(F.avg("temperature_c")).first()[0]
df_updated = df_updated.withColumn(
    "corrected_temperature",
    F.coalesce(F.col("temperature_c"), F.lit(average_temperature))
)

df_updated.show(10)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+----------+-------------+--------------+---------------+----------------+----------+---------------------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|     units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s| quality_status|maintenance_flag|supervisor|corrected_temperature|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+----------+-------------+--------------+---------------+----------------+----------+---------------------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|            1113.0|           993|             30|              34|    388.11|         61.4|          3.88|Requires Review|              No|    Charan|                 61.4|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|             809.0|           836|              0|               0|    398.58|        64.37|          2.28|         Failed|              No|     Farah|                64.37|
|    PR0000003|     2026-05-20|    PL01|     MC002|     OP0189|Evening|     MTR-300|        Motors|             464.1|           380|             17|              15|    183.34|        54.13|          4.66|         Failed|              No|     Deepa|                54.13|
|    PR0000004|     2026-01-15|    PL03|     MC013|     OP0076|Morning|     PMP-210|         Pumps|             787.0|           720|              7|              39|    217.61|        64.47|          NULL|Requires Review|              No|     Farah|                64.47|
|    PR0000005|     2026-09-21|    PL04|     MC020|     OP0501|Morning|     PMP-110|         Pumps|             344.0|           296|              7|              49|    115.47|        72.59|          3.21|           Pass|              No|     Deepa|                72.59|
|    PR0000006|     2026-09-03|    PL01|     MC002|     OP0501|Evening|     MTR-300|        Motors|1005.9000000000001|           795|             50|              44|    290.26|        64.91|          2.77|Requires Review|              No|     Gopal|                64.91|
|    PR0000007|     2026-05-07|    PL02|     MC007|     OP0645|Morning|     VLV-120|        Valves|            1165.0|           955|             10|               5|    355.56|        62.76|          2.89|           Pass|              No|     Gopal|                62.76|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|             862.0|           895|             51|              77|  274.0418|         57.1|          1.34|         Failed|              No|     Irfan|                 57.1|
|    PR0000009|     2026-03-10|    PL03|     MC015|     OP0386|Evening|     CTL-130|   Controllers|             313.0|           289|              8|              16|     87.62|        66.55|          3.07|           Pass|             Yes| Anita Rao|                66.55|
|    PR0000010|     2026-02-13|    PL02|     MC006|     OP0593|Evening|     CTL-230|   Controllers|             532.0|           527|             26|              64|    112.17|        60.96|          3.48|         Failed|              No|     Gopal|                60.96|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+------------------+--------------+---------------+----------------+----------+-------------+--------------+---------------+----------------+----------+---------------------+
only showing top 10 rows

In [111]:
print("Missing operator IDs:", df.filter(
    F.col("operator_id").isNull() | (F.trim(F.col("operator_id")) == "")
).count())

Missing operator IDs: 1524

In [112]:
print("Missing temperature:", df.filter(F.col("temperature_c").isNull()).count())

Missing temperature: 2132

In [113]:
print("Missing vibration:", df.filter(F.col("vibration_mm_s").isNull()).count())

Missing vibration: 1788

In [115]:
print("Missing downtime:", df.filter(F.col("downtime_minutes").isNull()).count())

Missing downtime: 1177

In [116]:
df_drop_any_null = df.na.drop()
print("Rows after na.drop():", df_drop_any_null.count())

Rows after na.drop(): 113531

In [117]:
df_drop_temperature_null = df.na.drop(subset=["temperature_c"])
print("Rows after dropping missing temperature:", df_drop_temperature_null.count())

Rows after dropping missing temperature: 117868

In [118]:
df_fill_downtime = df.na.fill({"downtime_minutes": 0})

In [119]:
df_fill_operator = df.na.fill({"operator_id": "UNKNOWN"})

In [120]:
avg_temp = df.agg(F.avg("temperature_c")).first()[0]
df_fill_temperature = df.na.fill({"temperature_c": avg_temp})

In [121]:
print("Before cleansing:", df.count())
print("After dropping any null:", df_drop_any_null.count())
print("After dropping only missing temperature:", df_drop_temperature_null.count())

Before cleansing: 120000
After dropping any null: 113531
After dropping only missing temperature: 117868

In [122]:
df.withColumn("product_family_upper", F.upper("product_family")).select(
    "product_family", "product_family_upper"
).show(10)

+--------------+--------------------+
|product_family|product_family_upper|
+--------------+--------------------+
|        Motors|              MOTORS|
|   Controllers|         CONTROLLERS|
|        Motors|              MOTORS|
|         Pumps|               PUMPS|
|         Pumps|               PUMPS|
|        Motors|              MOTORS|
|        Valves|              VALVES|
|        Valves|              VALVES|
|   Controllers|         CONTROLLERS|
|   Controllers|         CONTROLLERS|
+--------------+--------------------+
only showing top 10 rows

In [123]:
df.withColumn("supervisor_lower", F.lower("supervisor")).select(
    "supervisor", "supervisor_lower"
).show(10)

+----------+----------------+
|supervisor|supervisor_lower|
+----------+----------------+
|    Charan|          charan|
|     Farah|           farah|
|     Deepa|           deepa|
|     Farah|           farah|
|     Deepa|           deepa|
|     Gopal|           gopal|
|     Gopal|           gopal|
|     Irfan|           irfan|
|     Anita|           anita|
|     Gopal|           gopal|
+----------+----------------+
only showing top 10 rows

In [124]:
df.withColumn("operator_id_trimmed", F.trim("operator_id")).select(
    "operator_id", "operator_id_trimmed"
).show(10)

+-----------+-------------------+
|operator_id|operator_id_trimmed|
+-----------+-------------------+
|     OP0275|             OP0275|
|     OP0489|             OP0489|
|     OP0189|             OP0189|
|     OP0076|             OP0076|
|     OP0501|             OP0501|
|     OP0501|             OP0501|
|     OP0645|             OP0645|
|     OP0106|             OP0106|
|     OP0386|             OP0386|
|     OP0593|             OP0593|
+-----------+-------------------+
only showing top 10 rows

In [125]:
df.withColumn("product_code_length", F.length("product_code")).select(
    "product_code", "product_code_length"
).show(10)

+------------+-------------------+
|product_code|product_code_length|
+------------+-------------------+
|     MTR-100|                  7|
|     CTL-330|                  7|
|     MTR-300|                  7|
|     PMP-210|                  7|
|     PMP-110|                  7|
|     MTR-300|                  7|
|     VLV-120|                  7|
|     VLV-320|                  7|
|     CTL-130|                  7|
|     CTL-230|                  7|
+------------+-------------------+
only showing top 10 rows

In [126]:
df.withColumn("plant_machine", F.concat_ws("-", "plant_id", "machine_id")).select(
    "plant_id", "machine_id", "plant_machine"
).show(10)

+--------+----------+-------------+
|plant_id|machine_id|plant_machine|
+--------+----------+-------------+
|    PL03|     MC011|   PL03-MC011|
|    PL04|     MC019|   PL04-MC019|
|    PL01|     MC002|   PL01-MC002|
|    PL03|     MC013|   PL03-MC013|
|    PL04|     MC020|   PL04-MC020|
|    PL01|     MC002|   PL01-MC002|
|    PL02|     MC007|   PL02-MC007|
|    PL02|     MC009|   PL02-MC009|
|    PL03|     MC015|   PL03-MC015|
|    PL02|     MC006|   PL02-MC006|
+--------+----------+-------------+
only showing top 10 rows

In [127]:
df.withColumn("temperature_rounded", F.round("temperature_c", 1)).select(
    "temperature_c", "temperature_rounded"
).show(10)

+-------------+-------------------+
|temperature_c|temperature_rounded|
+-------------+-------------------+
|         61.4|               61.4|
|        64.37|               64.4|
|        54.13|               54.1|
|        64.47|               64.5|
|        72.59|               72.6|
|        64.91|               64.9|
|        62.76|               62.8|
|         57.1|               57.1|
|        66.55|               66.6|
|        60.96|               61.0|
+-------------+-------------------+
only showing top 10 rows

In [128]:
df.withColumn(
    "production_difference",
    F.abs(F.col("units_planned") - F.col("units_produced"))
).select("units_planned", "units_produced", "production_difference").show(10)

+-------------+--------------+---------------------+
|units_planned|units_produced|production_difference|
+-------------+--------------+---------------------+
|         1060|           993|                   67|
|          809|           836|                   27|
|          442|           380|                   62|
|          787|           720|                   67|
|          344|           296|                   48|
|          958|           795|                  163|
|         1165|           955|                  210|
|          862|           895|                   33|
|          313|           289|                   24|
|          532|           527|                    5|
+-------------+--------------+---------------------+
only showing top 10 rows

In [129]:
df.withColumn(
    "production_id_replaced",
    F.regexp_replace("production_id", "PR", "PROD-")
).select("production_id", "production_id_replaced").show(10)

+-------------+----------------------+
|production_id|production_id_replaced|
+-------------+----------------------+
|    PR0000001|          PROD-0000001|
|    PR0000002|          PROD-0000002|
|    PR0000003|          PROD-0000003|
|    PR0000004|          PROD-0000004|
|    PR0000005|          PROD-0000005|
|    PR0000006|          PROD-0000006|
|    PR0000007|          PROD-0000007|
|    PR0000008|          PROD-0000008|
|    PR0000009|          PROD-0000009|
|    PR0000010|          PROD-0000010|
+-------------+----------------------+
only showing top 10 rows

In [130]:
df.withColumn("product_code_prefix", F.substring("product_code", 1, 3)).select(
    "product_code", "product_code_prefix"
).show(10)

+------------+-------------------+
|product_code|product_code_prefix|
+------------+-------------------+
|     MTR-100|                MTR|
|     CTL-330|                CTL|
|     MTR-300|                MTR|
|     PMP-210|                PMP|
|     PMP-110|                PMP|
|     MTR-300|                MTR|
|     VLV-120|                VLV|
|     VLV-320|                VLV|
|     CTL-130|                CTL|
|     CTL-230|                CTL|
+------------+-------------------+
only showing top 10 rows

In [131]:
df.withColumn(
    "temperature_default",
    F.coalesce(F.col("temperature_c"), F.lit(25.0))
).select("temperature_c", "temperature_default").show(10)

+-------------+-------------------+
|temperature_c|temperature_default|
+-------------+-------------------+
|         61.4|               61.4|
|        64.37|              64.37|
|        54.13|              54.13|
|        64.47|              64.47|
|        72.59|              72.59|
|        64.91|              64.91|
|        62.76|              62.76|
|         57.1|               57.1|
|        66.55|              66.55|
|        60.96|              60.96|
+-------------+-------------------+
only showing top 10 rows

In [132]:
df_categories = df.withColumn(
    "production_efficiency",
    F.when(F.col("units_planned") != 0,
           F.col("units_produced") / F.col("units_planned") * 100)
).withColumn(
    "efficiency_category",
    F.when(F.col("production_efficiency") >= 100, "Above Target")
     .when(F.col("production_efficiency") >= 95, "On Target")
     .when(F.col("production_efficiency") >= 85, "Below Target")
     .otherwise("Critical")
)

In [133]:
df_categories = df_categories.withColumn(
    "defect_category",
    F.when(F.col("defective_units") == 0, "Perfect")
     .when(F.col("defective_units") <= 10, "Normal")
     .when(F.col("defective_units") <= 25, "Attention")
     .otherwise("High Defect")
)

In [134]:
df_categories = df_categories.withColumn(
    "machine_condition",
    F.when(
        (F.col("temperature_c") > 75) | (F.col("vibration_mm_s") > 5.0),
        "Inspect"
    ).otherwise("Normal")
)

In [135]:
df_categories.select(
    "production_id", "production_efficiency", "efficiency_category",
    "defective_units", "defect_category", "temperature_c",
    "vibration_mm_s", "machine_condition"
).show(20)

+-------------+---------------------+-------------------+---------------+---------------+-------------+--------------+-----------------+
|production_id|production_efficiency|efficiency_category|defective_units|defect_category|temperature_c|vibration_mm_s|machine_condition|
+-------------+---------------------+-------------------+---------------+---------------+-------------+--------------+-----------------+
|    PR0000001|    93.67924528301886|       Below Target|             30|    High Defect|         61.4|          3.88|           Normal|
|    PR0000002|   103.33745364647713|       Above Target|              0|        Perfect|        64.37|          2.28|           Normal|
|    PR0000003|    85.97285067873304|       Below Target|             17|      Attention|        54.13|          4.66|           Normal|
|    PR0000004|     91.4866581956798|       Below Target|              7|         Normal|        64.47|          NULL|           Normal|
|    PR0000005|    86.04651162790698|       Below Target|              7|         Normal|        72.59|          3.21|           Normal|
|    PR0000006|    82.98538622129436|           Critical|             50|    High Defect|        64.91|          2.77|           Normal|
|    PR0000007|    81.97424892703863|           Critical|             10|         Normal|        62.76|          2.89|           Normal|
|    PR0000008|   103.82830626450117|       Above Target|             51|    High Defect|         57.1|          1.34|           Normal|
|    PR0000009|    92.33226837060703|       Below Target|              8|         Normal|        66.55|          3.07|           Normal|
|    PR0000010|    99.06015037593986|          On Target|             26|    High Defect|        60.96|          3.48|           Normal|
|    PR0000011|    88.73483535528595|       Below Target|             14|      Attention|        52.81|          3.46|           Normal|
|    PR0000012|    98.77551020408163|          On Target|             23|      Attention|        69.79|          3.43|           Normal|
|    PR0000013|    86.35458167330677|       Below Target|             27|    High Defect|        50.88|           5.7|          Inspect|
|    PR0000014|   101.78571428571428|       Above Target|              6|         Normal|         67.2|          3.12|           Normal|
|    PR0000015|    95.94843462246777|          On Target|              4|         Normal|        76.39|          2.81|          Inspect|
|    PR0000016|    84.13793103448276|           Critical|              0|        Perfect|        44.92|          4.81|           Normal|
|    PR0000017|             83.59375|           Critical|             28|    High Defect|        75.09|           4.0|          Inspect|
|    PR0000018|    86.69131238447319|       Below Target|             18|      Attention|        59.91|          3.87|           Normal|
|    PR0000019|    99.73753280839895|          On Target|             16|      Attention|        62.23|          4.29|           Normal|
|    PR0000020|    88.69969040247679|       Below Target|             13|      Attention|        76.92|          2.35|          Inspect|
+-------------+---------------------+-------------------+---------------+---------------+-------------+--------------+-----------------+
only showing top 20 rows

In [136]:
df_categories.groupBy("efficiency_category").count().show()

+-------------------+-----+
|efficiency_category|count|
+-------------------+-----+
|       Above Target|21735|
|          On Target|26825|
|       Below Target|54619|
|           Critical|16821|
+-------------------+-----+

In [137]:
df_categories.groupBy("defect_category").count().show()

+---------------+-----+
|defect_category|count|
+---------------+-----+
|      Attention|45745|
|        Perfect|11491|
|    High Defect|28058|
|         Normal|34706|
+---------------+-----+

In [138]:
df_categories.groupBy("machine_condition").count().show()

+-----------------+------+
|machine_condition| count|
+-----------------+------+
|          Inspect| 15578|
|           Normal|104422|
+-----------------+------+

In [140]:
from google.colab import files
uploaded = files.upload()

Saving machine_configurations.json to machine_configurations.json

In [141]:
machine_json = spark.read.option(
"multiline", "true"
).json("machine_configurations.json")

In [142]:
machine_json.printSchema()

root
 |-- capacity_per_hour: long (nullable = true)
 |-- installed_year: long (nullable = true)
 |-- machine_id: string (nullable = true)
 |-- machine_type: string (nullable = true)
 |-- maintenance: struct (nullable = true)
 |    |-- frequency_days: long (nullable = true)
 |    |-- last_service: string (nullable = true)
 |-- plant_id: string (nullable = true)
 |-- sensors: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- active: boolean (nullable = true)
 |    |    |-- sensor: string (nullable = true)
 |    |    |-- unit: string (nullable = true)
 |-- specifications: struct (nullable = true)
 |    |-- max_temperature_c: long (nullable = true)
 |    |-- rated_power_kw: long (nullable = true)
 |    |-- vibration_limit_mm_s: double (nullable = true)

In [143]:
machine_json.select("machine_id", "machine_type").show()

+----------+------------+
|machine_id|machine_type|
+----------+------------+
|     MC001|         CNC|
|     MC002|    Assembly|
|     MC003|     Casting|
|     MC004|     Welding|
|     MC005|     Testing|
|     MC006|         CNC|
|     MC007|    Assembly|
|     MC008|     Casting|
|     MC009|     Welding|
|     MC010|     Testing|
|     MC011|         CNC|
|     MC012|    Assembly|
|     MC013|     Casting|
|     MC014|     Welding|
|     MC015|     Testing|
|     MC016|         CNC|
|     MC017|    Assembly|
|     MC018|     Casting|
|     MC019|     Welding|
|     MC020|     Testing|
+----------+------------+
only showing top 20 rows

In [144]:
machine_json.select(
    "machine_id", F.col("specifications.rated_power_kw").alias("rated_power_kw")
).show()

+----------+--------------+
|machine_id|rated_power_kw|
+----------+--------------+
|     MC001|            22|
|     MC002|            22|
|     MC003|            55|
|     MC004|            22|
|     MC005|            30|
|     MC006|            30|
|     MC007|            22|
|     MC008|            55|
|     MC009|            30|
|     MC010|            55|
|     MC011|            30|
|     MC012|            55|
|     MC013|            30|
|     MC014|            30|
|     MC015|            45|
|     MC016|            30|
|     MC017|            30|
|     MC018|            30|
|     MC019|            30|
|     MC020|            15|
+----------+--------------+
only showing top 20 rows

In [145]:
machine_json.select(
    "machine_id", F.col("specifications.max_temperature_c").alias("max_temperature_c")
).show()

+----------+-----------------+
|machine_id|max_temperature_c|
+----------+-----------------+
|     MC001|               85|
|     MC002|               85|
|     MC003|               90|
|     MC004|               85|
|     MC005|               85|
|     MC006|               85|
|     MC007|               80|
|     MC008|               75|
|     MC009|               85|
|     MC010|               90|
|     MC011|               90|
|     MC012|               80|
|     MC013|               90|
|     MC014|               80|
|     MC015|               90|
|     MC016|               75|
|     MC017|               85|
|     MC018|               85|
|     MC019|               75|
|     MC020|               80|
+----------+-----------------+
only showing top 20 rows

In [146]:
machine_json.select(
    "machine_id", F.col("specifications.vibration_limit_mm_s").alias("vibration_limit_mm_s")
).show()

+----------+--------------------+
|machine_id|vibration_limit_mm_s|
+----------+--------------------+
|     MC001|                 5.0|
|     MC002|                 5.5|
|     MC003|                 4.5|
|     MC004|                 4.5|
|     MC005|                 4.5|
|     MC006|                 5.5|
|     MC007|                 4.5|
|     MC008|                 5.0|
|     MC009|                 5.5|
|     MC010|                 4.5|
|     MC011|                 6.0|
|     MC012|                 5.5|
|     MC013|                 5.0|
|     MC014|                 5.5|
|     MC015|                 4.5|
|     MC016|                 5.5|
|     MC017|                 4.5|
|     MC018|                 5.0|
|     MC019|                 5.0|
|     MC020|                 5.0|
+----------+--------------------+
only showing top 20 rows

In [147]:
machine_json.select(
    "machine_id", F.col("maintenance.frequency_days").alias("maintenance_frequency_days")
).show()

+----------+--------------------------+
|machine_id|maintenance_frequency_days|
+----------+--------------------------+
|     MC001|                        60|
|     MC002|                        60|
|     MC003|                        45|
|     MC004|                        60|
|     MC005|                        30|
|     MC006|                        60|
|     MC007|                        30|
|     MC008|                        30|
|     MC009|                        30|
|     MC010|                        45|
|     MC011|                        30|
|     MC012|                        30|
|     MC013|                        60|
|     MC014|                        90|
|     MC015|                        30|
|     MC016|                        45|
|     MC017|                        30|
|     MC018|                        30|
|     MC019|                        30|
|     MC020|                        45|
+----------+--------------------------+
only showing top 20 rows

In [148]:
machine_json.select("machine_id", "sensors").show()

+----------+--------------------+
|machine_id|             sensors|
+----------+--------------------+
|     MC001|[{true, temperatu...|
|     MC002|[{true, temperatu...|
|     MC003|[{true, temperatu...|
|     MC004|[{true, temperatu...|
|     MC005|[{true, temperatu...|
|     MC006|[{true, temperatu...|
|     MC007|[{true, temperatu...|
|     MC008|[{true, temperatu...|
|     MC009|[{true, temperatu...|
|     MC010|[{true, temperatu...|
|     MC011|[{true, temperatu...|
|     MC012|[{true, temperatu...|
|     MC013|[{true, temperatu...|
|     MC014|[{true, temperatu...|
|     MC015|[{true, temperatu...|
|     MC016|[{true, temperatu...|
|     MC017|[{true, temperatu...|
|     MC018|[{true, temperatu...|
|     MC019|[{true, temperatu...|
|     MC020|[{true, temperatu...|
+----------+--------------------+
only showing top 20 rows

In [149]:
machine_sensors = machine_json.select(
    "machine_id", "machine_type", F.explode("sensors").alias("sensor_info")
)
machine_sensors.select(
    "machine_id",
    "machine_type",
    F.col("sensor_info.sensor").alias("sensor"),
    F.col("sensor_info.unit").alias("unit"),
    F.col("sensor_info.active").alias("active")
).show()

+----------+------------+-----------+----+------+
|machine_id|machine_type|     sensor|unit|active|
+----------+------------+-----------+----+------+
|     MC001|         CNC|temperature|   C|  true|
|     MC001|         CNC|  vibration|mm/s|  true|
|     MC001|         CNC|     energy| kWh|  true|
|     MC002|    Assembly|temperature|   C|  true|
|     MC002|    Assembly|  vibration|mm/s|  true|
|     MC002|    Assembly|     energy| kWh|  true|
|     MC003|     Casting|temperature|   C|  true|
|     MC003|     Casting|  vibration|mm/s|  true|
|     MC003|     Casting|     energy| kWh|  true|
|     MC004|     Welding|temperature|   C|  true|
|     MC004|     Welding|  vibration|mm/s|  true|
|     MC004|     Welding|     energy| kWh|  true|
|     MC005|     Testing|temperature|   C|  true|
|     MC005|     Testing|  vibration|mm/s|  true|
|     MC005|     Testing|     energy| kWh|  true|
|     MC006|         CNC|temperature|   C|  true|
|     MC006|         CNC|  vibration|mm/s|  true|
|     MC006|         CNC|     energy| kWh|  true|
|     MC007|    Assembly|temperature|   C|  true|
|     MC007|    Assembly|  vibration|mm/s|  true|
+----------+------------+-----------+----+------+
only showing top 20 rows

In [150]:
active_temperature_machines = machine_json.filter(
    F.expr("exists(sensors, x -> x.sensor = 'temperature' AND x.active = true)")
)
active_temperature_machines.select("machine_id", "machine_type").show()

+----------+------------+
|machine_id|machine_type|
+----------+------------+
|     MC001|         CNC|
|     MC002|    Assembly|
|     MC003|     Casting|
|     MC004|     Welding|
|     MC005|     Testing|
|     MC006|         CNC|
|     MC007|    Assembly|
|     MC008|     Casting|
|     MC009|     Welding|
|     MC010|     Testing|
|     MC011|         CNC|
|     MC012|    Assembly|
|     MC013|     Casting|
|     MC014|     Welding|
|     MC015|     Testing|
|     MC016|         CNC|
|     MC017|    Assembly|
|     MC018|     Casting|
|     MC019|     Welding|
|     MC020|     Testing|
+----------+------------+
only showing top 20 rows

In [151]:
machine_config_flat = machine_json.select(
    "machine_id", "plant_id", "machine_type",
    F.col("specifications.rated_power_kw").alias("rated_power_kw"),
    F.col("specifications.max_temperature_c").alias("max_temperature_c"),
    F.col("specifications.vibration_limit_mm_s").alias("vibration_limit_mm_s"),
    F.col("maintenance.frequency_days").alias("maintenance_frequency_days")
)
production_with_config = df.join(
    machine_config_flat, on=["machine_id", "plant_id"], how="left"
)
production_with_config.show()

+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+------------+--------------+-----------------+--------------------+--------------------------+
|machine_id|plant_id|production_id|production_date|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|machine_type|rated_power_kw|max_temperature_c|vibration_limit_mm_s|maintenance_frequency_days|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+------------+--------------+-----------------+--------------------+--------------------------+
|     MC011|    PL03|    PR0000001|     2026-08-07|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|         CNC|            30|               90|                 6.0|                        30|
|     MC019|    PL04|    PR0000002|     2026-08-03|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|     Welding|            30|               75|                 5.0|                        30|
|     MC002|    PL01|    PR0000003|     2026-05-20|     OP0189|Evening|     MTR-300|        Motors|          442|           380|             17|              15|    183.34|        54.13|          4.66|        Reject|              No|     Deepa|    Assembly|            22|               85|                 5.5|                        60|
|     MC013|    PL03|    PR0000004|     2026-01-15|     OP0076|Morning|     PMP-210|         Pumps|          787|           720|              7|              39|    217.61|        64.47|          NULL|        Rework|              No|     Farah|     Casting|            30|               90|                 5.0|                        60|
|     MC020|    PL04|    PR0000005|     2026-09-21|     OP0501|Morning|     PMP-110|         Pumps|          344|           296|              7|              49|    115.47|        72.59|          3.21|          Pass|              No|     Deepa|     Testing|            15|               80|                 5.0|                        45|
|     MC002|    PL01|    PR0000006|     2026-09-03|     OP0501|Evening|     MTR-300|        Motors|          958|           795|             50|              44|    290.26|        64.91|          2.77|        Rework|              No|     Gopal|    Assembly|            22|               85|                 5.5|                        60|
|     MC007|    PL02|    PR0000007|     2026-05-07|     OP0645|Morning|     VLV-120|        Valves|         1165|           955|             10|               5|    355.56|        62.76|          2.89|          Pass|              No|     Gopal|    Assembly|            22|               80|                 4.5|                        30|
|     MC009|    PL02|    PR0000008|     2026-08-17|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|     Welding|            30|               85|                 5.5|                        30|
|     MC015|    PL03|    PR0000009|     2026-03-10|     OP0386|Evening|     CTL-130|   Controllers|          313|           289|              8|              16|     87.62|        66.55|          3.07|          Pass|             Yes|     Anita|     Testing|            45|               90|                 4.5|                        30|
|     MC006|    PL02|    PR0000010|     2026-02-13|     OP0593|Evening|     CTL-230|   Controllers|          532|           527|             26|              64|    112.17|        60.96|          3.48|        Reject|              No|     Gopal|         CNC|            30|               85|                 5.5|                        60|
|     MC012|    PL03|    PR0000011|     2026-09-29|     OP0141|  Night|     PMP-210|         Pumps|          577|           512|             14|              32|     127.0|        52.81|          3.46|          Pass|              No|    Bharat|    Assembly|            55|               80|                 5.5|                        30|
|     MC030|    PL06|    PR0000012|     2026-07-10|     OP0047|Evening|     CTL-330|   Controllers|          980|           968|             23|              38|    377.97|        69.79|          3.43|        Rework|              No|     Gopal|     Testing|            55|               75|                 5.5|                        45|
|     MC027|    PL06|    PR0000013|     2026-07-19|     OP0172|  Night|     CTL-330|   Controllers|         1004|           867|             27|              66|    388.61|        50.88|           5.7|          Pass|             Yes|     Deepa|    Assembly|            55|               90|                 5.5|                        60|
|     MC013|    PL03|    PR0000014|     2026-05-05|     OP0446|Morning|     VLV-220|        Valves|          448|           456|              6|               6|    108.83|         67.2|          3.12|          Pass|             Yes|     Deepa|     Casting|            30|               90|                 5.0|                        60|
|     MC007|    PL02|    PR0000015|     2026-03-15|     OP0238|Morning|     MTR-300|        Motors|         1086|          1042|              4|             172|    239.64|        76.39|          2.81|          Pass|              No|     Deepa|    Assembly|            22|               80|                 4.5|                        30|
|     MC020|    PL04|    PR0000016|     2026-03-03|     OP0013|Morning|     CTL-330|   Controllers|          870|           732|              0|              13|    289.55|        44.92|          4.81|          Pass|             Yes|     Irfan|     Testing|            15|               80|                 5.0|                        45|
|     MC011|    PL03|    PR0000017|     2026-08-04|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|         CNC|            30|               90|                 6.0|                        30|
|     MC012|    PL03|    PR0000018|     2026-01-30|     OP0162|Evening|     MTR-100|        Motors|          541|           469|             18|              36|    241.05|        59.91|          3.87|          Pass|              No|     Farah|    Assembly|            55|               80|                 5.5|                        30|
|     MC005|    PL01|    PR0000019|     2026-01-11|     OP0526|Morning|     VLV-320|        Valves|          381|           380|             16|              25|    137.99|        62.23|          4.29|          Pass|              No|     Deepa|     Testing|            30|               85|                 4.5|                        30|
|     MC014|    PL03|    PR0000020|     2026-02-18|     OP0563|Morning|     PMP-310|         Pumps|          646|           573|             13|              64|    277.73|        76.92|          2.35|          Pass|              No|     Irfan|     Welding|            30|               80|                 5.5|                        90|
+----------+--------+-------------+---------------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+------------+--------------+-----------------+--------------------+--------------------------+
only showing top 20 rows

In [152]:
extra_df = spark.read.csv(
"manufacturing_production_extra_12k.csv",
header=True,
inferSchema=True
)

In [159]:
main_count = df.count()
print(main_count)

120000

In [160]:
extra_count = extra_df.count()
extra_aligned = extra_df.select(df.columns)
print(extra_count)

12500

In [156]:
union_df = df.select(df.columns).union(extra_aligned)
print("union() count:", union_df.count())

union() count: 132500

In [157]:
if hasattr(df, "unionAll"):
    union_all_df = df.select(df.columns).unionAll(extra_aligned)
else:
    union_all_df = df.select(df.columns).union(extra_aligned)
print("unionAll() count:", union_all_df.count())

unionAll() count: 132500

In [158]:
print("Main + extra:", main_count + extra_count)
print("union count:", union_df.count())
print("unionAll count:", union_all_df.count())

Main + extra: 132500
union count: 132500
unionAll count: 132500

In [161]:
duplicate_ids = union_df.groupBy("production_id").count().filter(F.col("count") > 1)
duplicate_ids.show()

+-------------+-----+
|production_id|count|
+-------------+-----+
|    PR0000413|    2|
|    PR0000135|    2|
|    PR0000236|    2|
|    PR0000339|    2|
|    PR0000059|    2|
|    PR0000463|    2|
|    PR0000136|    2|
|    PR0000263|    2|
|    PR0000393|    2|
|    PR0000445|    2|
|    PR0000124|    2|
|    PR0000299|    2|
|    PR0000341|    2|
|    PR0000008|    2|
|    PR0000172|    2|
|    PR0000359|    2|
|    PR0000389|    2|
|    PR0000026|    2|
|    PR0000274|    2|
|    PR0000161|    2|
+-------------+-----+
only showing top 20 rows

In [162]:
union_distinct_rows = union_df.dropDuplicates()
print("Count after removing exact duplicate rows:", union_distinct_rows.count())

Count after removing exact duplicate rows: 132500

In [163]:
print("Before dropDuplicates:", union_df.count())
print("After dropDuplicates:", union_distinct_rows.count())

Before dropDuplicates: 132500
After dropDuplicates: 132500

In [164]:
union_by_name_df = df.unionByName(extra_df)
print("unionByName count:", union_by_name_df.count())

unionByName count: 132500

In [165]:
reordered_extra = extra_df.select(*list(reversed(extra_df.columns)))
union_by_name_reordered = df.unionByName(reordered_extra)
print("unionByName with reordered columns:", union_by_name_reordered.count())

unionByName with reordered columns: 132500

In [168]:
from pyspark.sql.window import Window
plant_output_window = Window.partitionBy("plant_id").orderBy(F.col("units_produced").desc())

In [169]:
df_ranked = df.withColumn("row_number", F.row_number().over(plant_output_window)) \
              .withColumn("rank", F.rank().over(plant_output_window)) \
              .withColumn("dense_rank", F.dense_rank().over(plant_output_window))
df_ranked.select(
    "plant_id", "production_id", "units_produced",
    "row_number", "rank", "dense_rank"
).show(20)

+--------+-------------+--------------+----------+----+----------+
|plant_id|production_id|units_produced|row_number|rank|dense_rank|
+--------+-------------+--------------+----------+----+----------+
|    PL01|    PR0073059|          1239|         1|   1|         1|
|    PL01|    PR0002678|          1238|         2|   2|         2|
|    PL01|    PR0005192|          1236|         3|   3|         3|
|    PL01|    PR0044516|          1236|         4|   3|         3|
|    PL01|    PR0056319|          1236|         5|   3|         3|
|    PL01|    PR0006350|          1234|         6|   6|         4|
|    PL01|    PR0046906|          1233|         7|   7|         5|
|    PL01|    PR0046582|          1230|         8|   8|         6|
|    PL01|    PR0024941|          1229|         9|   9|         7|
|    PL01|    PR0088933|          1229|        10|   9|         7|
|    PL01|    PR0097172|          1229|        11|   9|         7|
|    PL01|    PR0048075|          1228|        12|  12|         8|
|    PL01|    PR0083644|          1228|        13|  12|         8|
|    PL01|    PR0002284|          1227|        14|  14|         9|
|    PL01|    PR0109962|          1227|        15|  14|         9|
|    PL01|    PR0000300|          1226|        16|  16|        10|
|    PL01|    PR0012821|          1226|        17|  16|        10|
|    PL01|    PR0022084|          1226|        18|  16|        10|
|    PL01|    PR0083683|          1226|        19|  16|        10|
|    PL01|    PR0119269|          1226|        20|  16|        10|
+--------+-------------+--------------+----------+----+----------+
only showing top 20 rows

In [170]:
df_ranked.filter(F.col("row_number") <= 5).orderBy(
    "plant_id", "row_number"
).show(100)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+----+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|row_number|rank|dense_rank|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+----+----------+
|    PR0073059|     2026-04-01|    PL01|     MC003|     OP0110|Evening|     MTR-200|        Motors|         1198|          1239|             11|               0|     282.6|        50.32|          3.91|        Rework|              No|     Gopal|         1|   1|         1|
|    PR0002678|     2026-04-06|    PL01|     MC005|     OP0509|  Night|     CTL-130|   Controllers|         1194|          1238|             68|              30|    305.77|        69.09|          3.41|        Reject|              No|    Harini|         2|   2|         2|
|    PR0005192|     2026-09-08|    PL01|     MC002|     OP0075|Morning|     MTR-300|        Motors|         1195|          1236|             12|              49|    349.97|         81.8|          2.95|          Pass|              No|     Gopal|         3|   3|         3|
|    PR0044516|     2026-10-10|    PL01|     MC002|     OP0513|Morning|     MTR-200|        Motors|         1200|          1236|             25|              37|    233.63|        75.95|          1.82|          Pass|              No|     Gopal|         4|   3|         3|
|    PR0056319|     2026-06-07|    PL01|     MC002|     OP0453|Evening|     CTL-130|   Controllers|         1193|          1236|              4|              24|    617.25|        46.98|          4.71|          Pass|             Yes|     Farah|         5|   3|         3|
|    PR0100473|     2026-10-18|    PL02|     MC009|     OP0559|  Night|     CTL-230|   Controllers|         1198|          1245|             53|              16|    375.27|         58.3|          2.82|        Reject|              No|     Irfan|         1|   1|         1|
|    PR0010732|     2026-09-26|    PL02|     MC007|     OP0496|Evening|     PMP-210|         Pumps|         1200|          1243|              0|               0|    599.61|        75.16|           1.8|          Pass|              No|     Gopal|         2|   2|         2|
|    PR0001765|     2026-09-15|    PL02|     MC006|     OP0088|  Night|     MTR-300|        Motors|         1195|          1242|              0|               0|    303.92|        58.93|          4.05|        Reject|             Yes|     Deepa|         3|   3|         3|
|    PR0027036|     2026-08-03|    PL02|     MC010|     OP0285|Morning|     MTR-200|        Motors|         1191|          1238|             12|              64|    583.51|         NULL|          2.95|          Pass|              No|    Charan|         4|   4|         4|
|    PR0012982|     2026-05-07|    PL02|     MC009|     OP0405|Evening|     CTL-330|   Controllers|         1194|          1237|              4|               0|    275.64|        68.43|          5.18|          Pass|              No|    Bharat|         5|   5|         5|
|    PR0082579|     2026-01-20|    PL03|     MC013|     OP0313|Morning|     MTR-100|        Motors|         1200|          1243|              1|              40|    517.17|        51.05|          3.65|        Rework|              No|    Charan|         1|   1|         1|
|    PR0030298|     2026-05-04|    PL03|     MC011|     OP0514|  Night|     CTL-130|   Controllers|         1195|          1239|             30|              74|    616.84|        60.83|          5.16|          Pass|              No|    Harini|         2|   2|         2|
|    PR0117602|     2026-02-13|    PL03|     MC012|     OP0368|Evening|     MTR-100|        Motors|         1197|          1239|             27|              38|    521.93|        69.64|          2.28|          Pass|              No|    Bharat|         3|   2|         2|
|    PR0102987|     2026-07-07|    PL03|     MC015|     OP0220|Morning|     PMP-310|         Pumps|         1192|          1236|             10|               1|    304.23|        71.75|          3.49|          Pass|              No|     Farah|         4|   4|         3|
|    PR0021534|     2026-06-14|    PL03|     MC011|     OP0042|  Night|     MTR-100|        Motors|         1189|          1235|             46|              53|    507.11|        60.86|          1.71|          Pass|             Yes|    Charan|         5|   5|         4|
|    PR0008535|     2026-02-23|    PL04|     MC018|     OP0286|Morning|     MTR-200|        Motors|         1199|          1245|              0|              53|    257.72|        60.24|           2.6|          Pass|              No|     Farah|         1|   1|         1|
|    PR0087560|     2026-06-29|    PL04|     MC018|     OP0587|  Night|     VLV-120|        Valves|         1199|          1245|             60|               0|    500.87|        58.11|          3.58|          Pass|             Yes|    Charan|         2|   1|         1|
|    PR0047939|     2026-09-28|    PL04|     MC020|     OP0174|Evening|     PMP-210|         Pumps|         1199|          1243|             42|              28|    502.25|        66.71|          2.97|          Pass|              No|     Anita|         3|   3|         2|
|    PR0069661|     2026-01-28|    PL04|     MC020|     OP0499|Evening|     CTL-130|   Controllers|         1200|          1242|             13|              40|     392.3|         NULL|           2.7|          Pass|             Yes|     Irfan|         4|   4|         3|
|    PR0093782|     2026-06-01|    PL04|     MC020|     OP0240|Evening|     VLV-320|        Valves|         1192|          1239|             10|               0|    257.87|         62.6|          4.35|        Rework|              No|     Anita|         5|   5|         4|
|    PR0098612|     2026-09-02|    PL05|     MC024|     OP0268|Morning|     PMP-210|         Pumps|         1199|          1245|             23|               0|    350.65|        56.41|          2.13|          Pass|              No|    Bharat|         1|   1|         1|
|    PR0116814|     2026-04-16|    PL05|     MC022|     OP0125|Evening|     CTL-130|   Controllers|         1200|          1240|             22|              50|    515.01|        68.24|          3.18|          Pass|              No|    Charan|         2|   2|         2|
|    PR0103247|     2026-10-12|    PL05|     MC024|     OP0529|  Night|     CTL-230|   Controllers|         1195|          1239|             39|             165|    617.61|        69.15|          3.33|          Pass|              No|     Deepa|         3|   3|         3|
|    PR0020622|     2026-09-20|    PL05|     MC021|     OP0580|Evening|     VLV-320|        Valves|         1191|          1238|             57|              32|     639.8|        69.02|          3.63|          Pass|              No|    Harini|         4|   4|         4|
|    PR0033781|     2026-04-18|    PL05|     MC022|     OP0254|Evening|     PMP-310|         Pumps|         1200|          1238|             36|              41|    617.76|        72.83|           4.8|          Pass|              No|    Charan|         5|   4|         4|
|    PR0064142|     2026-01-10|    PL06|     MC028|     OP0332|Morning|     PMP-310|         Pumps|         1195|          1241|             39|              41|    547.34|        77.31|          3.18|          Pass|              No|    Harini|         1|   1|         1|
|    PR0103306|     2026-06-09|    PL06|     MC026|     OP0015|  Night|     PMP-110|         Pumps|         1197|          1239|             30|              19|    390.78|        62.21|          2.96|          Pass|             Yes|     Farah|         2|   2|         2|
|    PR0070732|     2026-07-24|    PL06|     MC027|     OP0336|Morning|     VLV-120|        Valves|         1196|          1237|             62|              52|    496.14|        61.64|          3.67|        Rework|              No|    Charan|         3|   3|         3|
|    PR0016289|     2026-07-11|    PL06|     MC028|     OP0228|Evening|     PMP-310|         Pumps|         1190|          1235|             12|              48|    621.59|        55.47|          2.75|          Pass|              No|     Deepa|         4|   4|         4|
|    PR0091874|     2026-07-22|    PL06|     MC030|     OP0506|  Night|     PMP-310|         Pumps|         1198|          1229|             49|             184|    296.58|        56.31|          2.29|          Pass|              No|     Irfan|         5|   5|         5|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----------+----+----------+

In [171]:
machine_output = df.groupBy("plant_id", "machine_id").agg(
    F.sum("units_produced").alias("total_output")
)
machine_window = Window.partitionBy("plant_id").orderBy(F.col("total_output").desc())
top_machines = machine_output.withColumn(
    "machine_rank", F.row_number().over(machine_window)
).filter(F.col("machine_rank") <= 3)
top_machines.orderBy("plant_id", "machine_rank").show()

+--------+----------+------------+------------+
|plant_id|machine_id|total_output|machine_rank|
+--------+----------+------------+------------+
|    PL01|     MC004|     2722412|           1|
|    PL01|     MC002|     2713779|           2|
|    PL01|     MC001|     2691431|           3|
|    PL02|     MC009|     2760070|           1|
|    PL02|     MC007|     2713038|           2|
|    PL02|     MC008|     2705850|           3|
|    PL03|     MC012|     2750570|           1|
|    PL03|     MC015|     2739284|           2|
|    PL03|     MC014|     2735500|           3|
|    PL04|     MC016|     2750780|           1|
|    PL04|     MC019|     2735839|           2|
|    PL04|     MC017|     2726300|           3|
|    PL05|     MC024|     2737331|           1|
|    PL05|     MC023|     2718075|           2|
|    PL05|     MC022|     2635629|           3|
|    PL06|     MC026|     2723306|           1|
|    PL06|     MC027|     2718877|           2|
|    PL06|     MC030|     2701993|           3|
+--------+----------+------------+------------+

In [172]:
plant_total_window = Window.partitionBy("plant_id")
df.withColumn(
    "plant_total_production", F.sum("units_produced").over(plant_total_window)
).select("production_id", "plant_id", "units_produced", "plant_total_production").show(10)

+-------------+--------+--------------+----------------------+
|production_id|plant_id|units_produced|plant_total_production|
+-------------+--------+--------------+----------------------+
|    PR0000003|    PL01|           380|              13488232|
|    PR0000006|    PL01|           795|              13488232|
|    PR0000019|    PL01|           380|              13488232|
|    PR0000026|    PL01|           663|              13488232|
|    PR0000028|    PL01|          1042|              13488232|
|    PR0000030|    PL01|           359|              13488232|
|    PR0000031|    PL01|           776|              13488232|
|    PR0000039|    PL01|           265|              13488232|
|    PR0000040|    PL01|           306|              13488232|
|    PR0000050|    PL01|           908|              13488232|
+-------------+--------+--------------+----------------------+
only showing top 10 rows

In [173]:
machine_window_all = Window.partitionBy("machine_id")
df.withColumn(
    "machine_average_output", F.avg("units_produced").over(machine_window_all)
).select("production_id", "machine_id", "units_produced", "machine_average_output").show(10)

+-------------+----------+--------------+----------------------+
|production_id|machine_id|units_produced|machine_average_output|
+-------------+----------+--------------+----------------------+
|    PR0000026|     MC001|           663|     671.5147205588822|
|    PR0000057|     MC001|           325|     671.5147205588822|
|    PR0000088|     MC001|           676|     671.5147205588822|
|    PR0000135|     MC001|           375|     671.5147205588822|
|    PR0000139|     MC001|           378|     671.5147205588822|
|    PR0000159|     MC001|           762|     671.5147205588822|
|    PR0000216|     MC001|           431|     671.5147205588822|
|    PR0000232|     MC001|          1030|     671.5147205588822|
|    PR0000243|     MC001|           464|     671.5147205588822|
|    PR0000279|     MC001|           616|     671.5147205588822|
+-------------+----------+--------------+----------------------+
only showing top 10 rows

In [174]:
date_window = Window.partitionBy("machine_id").orderBy("production_date", "production_id")
df_windowed = df.withColumn(
    "cumulative_production",
    F.sum("units_produced").over(date_window.rowsBetween(Window.unboundedPreceding, Window.currentRow))
).withColumn(
    "previous_output", F.lag("units_produced").over(date_window)
).withColumn(
    "next_output", F.lead("units_produced").over(date_window)
).withColumn(
    "change_from_previous",
    F.col("units_produced") - F.lag("units_produced").over(date_window)
)
df_windowed.select(
    "machine_id", "production_date", "units_produced", "cumulative_production",
    "previous_output", "next_output", "change_from_previous"
).show(20)

+----------+---------------+--------------+---------------------+---------------+-----------+--------------------+
|machine_id|production_date|units_produced|cumulative_production|previous_output|next_output|change_from_previous|
+----------+---------------+--------------+---------------------+---------------+-----------+--------------------+
|     MC001|     2026-01-01|           437|                  437|           NULL|        997|                NULL|
|     MC001|     2026-01-01|           997|                 1434|            437|        822|                 560|
|     MC001|     2026-01-01|           822|                 2256|            997|        817|                -175|
|     MC001|     2026-01-01|           817|                 3073|            822|        784|                  -5|
|     MC001|     2026-01-01|           784|                 3857|            817|        472|                 -33|
|     MC001|     2026-01-01|           472|                 4329|            784|       1078|                -312|
|     MC001|     2026-01-01|          1078|                 5407|            472|       1027|                 606|
|     MC001|     2026-01-01|          1027|                 6434|           1078|       1023|                 -51|
|     MC001|     2026-01-01|          1023|                 7457|           1027|        257|                  -4|
|     MC001|     2026-01-01|           257|                 7714|           1023|        929|                -766|
|     MC001|     2026-01-01|           929|                 8643|            257|        926|                 672|
|     MC001|     2026-01-01|           926|                 9569|            929|        799|                  -3|
|     MC001|     2026-01-01|           799|                10368|            926|        560|                -127|
|     MC001|     2026-01-01|           560|                10928|            799|       1157|                -239|
|     MC001|     2026-01-01|          1157|                12085|            560|        536|                 597|
|     MC001|     2026-01-01|           536|                12621|           1157|        519|                -621|
|     MC001|     2026-01-02|           519|                13140|            536|        487|                 -17|
|     MC001|     2026-01-02|           487|                13627|            519|        611|                 -32|
|     MC001|     2026-01-02|           611|                14238|            487|        952|                 124|
|     MC001|     2026-01-02|           952|                15190|            611|        485|                 341|
+----------+---------------+--------------+---------------------+---------------+-----------+--------------------+
only showing top 20 rows

In [175]:
family_output = df.groupBy("product_family").agg(
    F.sum("units_produced").alias("total_output")
)
family_rank_window = Window.orderBy(F.col("total_output").desc())
family_output.withColumn(
    "family_rank", F.dense_rank().over(family_rank_window)
).orderBy("family_rank").show()

+--------------+------------+-----------+
|product_family|total_output|family_rank|
+--------------+------------+-----------+
|        Valves|    20433082|          1|
|         Pumps|    20208739|          2|
|   Controllers|    20168572|          3|
|        Motors|    20117495|          4|
+--------------+------------+-----------+

In [176]:
df_dates = df.withColumn("production_date", F.to_date("production_date"))

In [177]:
df_dates.select("production_date").printSchema()

root
 |-- production_date: date (nullable = true)

In [178]:
df_dates = df_dates.withColumn("year", F.year("production_date"))

In [179]:
df_dates = df_dates.withColumn("month", F.month("production_date"))

In [180]:
df_dates = df_dates.withColumn("day", F.dayofmonth("production_date"))

In [181]:
df_dates = df_dates.withColumn("month_name", F.date_format("production_date", "MMMM"))

In [182]:
df_dates = df_dates.withColumn("day_name", F.date_format("production_date", "EEEE"))

In [184]:
df_dates = df_dates.withColumn("year_month", F.date_format("production_date", "yyyy-MM"))
df_dates.select(
    "production_date", "year", "month", "day", "month_name", "day_name", "year_month"
).show(20)

+---------------+----+-----+---+----------+---------+----------+
|production_date|year|month|day|month_name| day_name|year_month|
+---------------+----+-----+---+----------+---------+----------+
|     2026-08-07|2026|    8|  7|    August|   Friday|   2026-08|
|     2026-08-03|2026|    8|  3|    August|   Monday|   2026-08|
|     2026-05-20|2026|    5| 20|       May|Wednesday|   2026-05|
|     2026-01-15|2026|    1| 15|   January| Thursday|   2026-01|
|     2026-09-21|2026|    9| 21| September|   Monday|   2026-09|
|     2026-09-03|2026|    9|  3| September| Thursday|   2026-09|
|     2026-05-07|2026|    5|  7|       May| Thursday|   2026-05|
|     2026-08-17|2026|    8| 17|    August|   Monday|   2026-08|
|     2026-03-10|2026|    3| 10|     March|  Tuesday|   2026-03|
|     2026-02-13|2026|    2| 13|  February|   Friday|   2026-02|
|     2026-09-29|2026|    9| 29| September|  Tuesday|   2026-09|
|     2026-07-10|2026|    7| 10|      July|   Friday|   2026-07|
|     2026-07-19|2026|    7| 19|      July|   Sunday|   2026-07|
|     2026-05-05|2026|    5|  5|       May|  Tuesday|   2026-05|
|     2026-03-15|2026|    3| 15|     March|   Sunday|   2026-03|
|     2026-03-03|2026|    3|  3|     March|  Tuesday|   2026-03|
|     2026-08-04|2026|    8|  4|    August|  Tuesday|   2026-08|
|     2026-01-30|2026|    1| 30|   January|   Friday|   2026-01|
|     2026-01-11|2026|    1| 11|   January|   Sunday|   2026-01|
|     2026-02-18|2026|    2| 18|  February|Wednesday|   2026-02|
+---------------+----+-----+---+----------+---------+----------+
only showing top 20 rows

In [185]:
df_dates.groupBy("year_month").agg(
    F.sum("units_produced").alias("monthly_production")
).orderBy("year_month").show()

+----------+------------------+
|year_month|monthly_production|
+----------+------------------+
|   2026-01|           8478059|
|   2026-02|           7810891|
|   2026-03|           8441121|
|   2026-04|           8211005|
|   2026-05|           8507542|
|   2026-06|           8400505|
|   2026-07|           8476416|
|   2026-08|           8529150|
|   2026-09|           8115221|
|   2026-10|           5957978|
+----------+------------------+

In [186]:
df_dates.groupBy("year_month").agg(
    F.sum("defective_units").alias("monthly_defects")
).orderBy("year_month").show()

+----------+---------------+
|year_month|monthly_defects|
+----------+---------------+
|   2026-01|         211741|
|   2026-02|         197462|
|   2026-03|         212036|
|   2026-04|         208707|
|   2026-05|         212049|
|   2026-06|         210381|
|   2026-07|         210482|
|   2026-08|         214807|
|   2026-09|         202990|
|   2026-10|         149589|
+----------+---------------+

In [187]:
df_dates.groupBy("year_month", "plant_id").agg(
    F.sum("units_produced").alias("monthly_production")
).orderBy("year_month", "plant_id").show()

+----------+--------+------------------+
|year_month|plant_id|monthly_production|
+----------+--------+------------------+
|   2026-01|    PL01|           1451436|
|   2026-01|    PL02|           1419252|
|   2026-01|    PL03|           1429811|
|   2026-01|    PL04|           1399488|
|   2026-01|    PL05|           1375887|
|   2026-01|    PL06|           1402185|
|   2026-02|    PL01|           1342273|
|   2026-02|    PL02|           1278581|
|   2026-02|    PL03|           1305531|
|   2026-02|    PL04|           1292557|
|   2026-02|    PL05|           1324271|
|   2026-02|    PL06|           1267678|
|   2026-03|    PL01|           1442140|
|   2026-03|    PL02|           1359740|
|   2026-03|    PL03|           1416484|
|   2026-03|    PL04|           1447603|
|   2026-03|    PL05|           1411435|
|   2026-03|    PL06|           1363719|
|   2026-04|    PL01|           1350450|
|   2026-04|    PL02|           1369684|
+----------+--------+------------------+
only showing top 20 rows

In [188]:
df_dates.filter(
    F.col("production_date").between(F.to_date(F.lit("2026-08-01")),
                                     F.to_date(F.lit("2026-08-31")))
).show(20)

+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
|production_id|production_date|plant_id|machine_id|operator_id|  shift|product_code|product_family|units_planned|units_produced|defective_units|downtime_minutes|energy_kwh|temperature_c|vibration_mm_s|quality_status|maintenance_flag|supervisor|year|month|day|month_name| day_name|year_month|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
|    PR0000001|     2026-08-07|    PL03|     MC011|     OP0275|Evening|     MTR-100|        Motors|         1060|           993|             30|              34|    388.11|         61.4|          3.88|        Rework|              No|    Charan|2026|    8|  7|    August|   Friday|   2026-08|
|    PR0000002|     2026-08-03|    PL04|     MC019|     OP0489|Morning|     CTL-330|   Controllers|          809|           836|              0|               0|    398.58|        64.37|          2.28|        Reject|              No|     Farah|2026|    8|  3|    August|   Monday|   2026-08|
|    PR0000008|     2026-08-17|    PL02|     MC009|     OP0106|  Night|     VLV-320|        Valves|          862|           895|             51|              77|    266.06|         57.1|          1.34|        Reject|              No|     Irfan|2026|    8| 17|    August|   Monday|   2026-08|
|    PR0000017|     2026-08-04|    PL03|     MC011|     OP0533|Morning|     CTL-330|   Controllers|         1152|           963|             28|              91|    347.34|        75.09|           4.0|          Pass|             Yes|     Gopal|2026|    8|  4|    August|  Tuesday|   2026-08|
|    PR0000066|     2026-08-13|    PL04|     MC019|     OP0015|Morning|     VLV-120|        Valves|          948|           901|             16|              13|    424.26|        52.29|          2.23|          Pass|              No|    Bharat|2026|    8| 13|    August| Thursday|   2026-08|
|    PR0000070|     2026-08-29|    PL04|     MC017|     OP0460|Morning|     CTL-230|   Controllers|          614|           625|             33|              42|    200.11|        76.02|           5.2|        Reject|             Yes|     Farah|2026|    8| 29|    August| Saturday|   2026-08|
|    PR0000081|     2026-08-06|    PL06|     MC029|     OP0610|Morning|     VLV-220|        Valves|          723|           616|             13|               0|    252.28|         70.6|          4.01|          Pass|              No|     Deepa|2026|    8|  6|    August| Thursday|   2026-08|
|    PR0000103|     2026-08-12|    PL06|     MC027|     OP0367|  Night|     CTL-330|   Controllers|          371|           345|              9|               9|     89.48|        65.68|          3.32|        Rework|              No|     Irfan|2026|    8| 12|    August|Wednesday|   2026-08|
|    PR0000106|     2026-08-06|    PL04|     MC018|     OP0213|  Night|     CTL-130|   Controllers|         1191|          1176|              0|               0|    571.57|        48.59|          2.49|          Pass|              No|     Irfan|2026|    8|  6|    August| Thursday|   2026-08|
|    PR0000112|     2026-08-29|    PL06|     MC030|     OP0490|Evening|     PMP-310|         Pumps|          830|           786|             21|              82|    401.59|        64.32|          2.52|          Pass|              No|    Bharat|2026|    8| 29|    August| Saturday|   2026-08|
|    PR0000115|     2026-08-04|    PL03|     MC014|     OP0633|Morning|     CTL-130|   Controllers|         1115|          1002|             20|               0|    371.92|        62.97|          3.98|          Pass|              No|    Charan|2026|    8|  4|    August|  Tuesday|   2026-08|
|    PR0000119|     2026-08-14|    PL02|     MC007|     OP0339|  Night|     MTR-200|        Motors|         1055|          1014|             20|              53|    515.92|        71.55|          3.19|        Rework|              No|    Charan|2026|    8| 14|    August|   Friday|   2026-08|
|    PR0000122|     2026-08-19|    PL04|     MC019|       NULL|Morning|     PMP-310|         Pumps|         1055|           871|             35|              35|    269.26|        70.01|          4.04|        Reject|              No|     Gopal|2026|    8| 19|    August|Wednesday|   2026-08|
|    PR0000123|     2026-08-09|    PL05|     MC023|     OP0216|Morning|     VLV-220|        Valves|         1042|           875|             26|               0|    259.89|        61.14|          1.83|          Pass|              No|    Bharat|2026|    8|  9|    August|   Sunday|   2026-08|
|    PR0000136|     2026-08-20|    PL04|     MC017|     OP0207|Morning|     PMP-210|         Pumps|          923|           767|             18|              26|    149.17|        58.53|          4.74|        Rework|              No|     Farah|2026|    8| 20|    August| Thursday|   2026-08|
|    PR0000137|     2026-08-18|    PL06|     MC029|     OP0412|  Night|     MTR-200|        Motors|          624|           612|             23|               0|    198.24|        67.26|          2.21|        Rework|             Yes|    Charan|2026|    8| 18|    August|  Tuesday|   2026-08|
|    PR0000146|     2026-08-19|    PL01|     MC005|     OP0088|  Night|     VLV-120|        Valves|         1156|           969|              0|               9|    501.65|        67.41|          5.76|        Rework|              No|    Bharat|2026|    8| 19|    August|Wednesday|   2026-08|
|    PR0000150|     2026-08-17|    PL05|     MC022|     OP0075|  Night|     VLV-320|        Valves|          840|           719|             19|              62|    336.24|        63.21|          2.77|          Pass|             Yes|    Charan|2026|    8| 17|    August|   Monday|   2026-08|
|    PR0000154|     2026-08-19|    PL01|     MC002|     OP0624|Morning|     PMP-310|         Pumps|          508|           450|              8|              43|    231.23|        53.02|           3.1|        Rework|              No|    Charan|2026|    8| 19|    August|Wednesday|   2026-08|
|    PR0000169|     2026-08-11|    PL02|     MC007|     OP0172|  Night|     MTR-100|        Motors|          573|           578|             12|             150|    273.34|        70.33|          4.89|          Pass|              No|     Deepa|2026|    8| 11|    August|  Tuesday|   2026-08|
+-------------+---------------+--------+----------+-----------+-------+------------+--------------+-------------+--------------+---------------+----------------+----------+-------------+--------------+--------------+----------------+----------+----+-----+---+----------+---------+----------+
only showing top 20 rows

In [189]:
df_dates.withColumn(
    "date_plus_7_days", F.date_add("production_date", 7)
).select("production_date", "date_plus_7_days").show(10)

+---------------+----------------+
|production_date|date_plus_7_days|
+---------------+----------------+
|     2026-08-07|      2026-08-14|
|     2026-08-03|      2026-08-10|
|     2026-05-20|      2026-05-27|
|     2026-01-15|      2026-01-22|
|     2026-09-21|      2026-09-28|
|     2026-09-03|      2026-09-10|
|     2026-05-07|      2026-05-14|
|     2026-08-17|      2026-08-24|
|     2026-03-10|      2026-03-17|
|     2026-02-13|      2026-02-20|
+---------------+----------------+
only showing top 10 rows

In [190]:
df_dates.withColumn(
    "date_minus_30_days", F.date_sub("production_date", 30)
).select("production_date", "date_minus_30_days").show(10)

+---------------+------------------+
|production_date|date_minus_30_days|
+---------------+------------------+
|     2026-08-07|        2026-07-08|
|     2026-08-03|        2026-07-04|
|     2026-05-20|        2026-04-20|
|     2026-01-15|        2025-12-16|
|     2026-09-21|        2026-08-22|
|     2026-09-03|        2026-08-04|
|     2026-05-07|        2026-04-07|
|     2026-08-17|        2026-07-18|
|     2026-03-10|        2026-02-08|
|     2026-02-13|        2026-01-14|
+---------------+------------------+
only showing top 10 rows

In [191]:
df_dates.withColumn(
    "days_from_current_date", F.datediff(F.current_date(), F.col("production_date"))
).select("production_date", "days_from_current_date").show(10)

+---------------+----------------------+
|production_date|days_from_current_date|
+---------------+----------------------+
|     2026-08-07|                    77|
|     2026-08-03|                    81|
|     2026-05-20|                   156|
|     2026-01-15|                   281|
|     2026-09-21|                    32|
|     2026-09-03|                    50|
|     2026-05-07|                   169|
|     2026-08-17|                    67|
|     2026-03-10|                   227|
|     2026-02-13|                   252|
+---------------+----------------------+
only showing top 10 rows

In [192]:
monthly_output = df_dates.groupBy("year_month").agg(
    F.sum("units_produced").alias("total_output")
)
monthly_output.orderBy(F.col("total_output").desc()).show(1, truncate=False)

+----------+------------+
|year_month|total_output|
+----------+------------+
|2026-08   |8529150     |
+----------+------------+
only showing top 1 row